// Generated by the Crawlora platform client generator. Do not edit.
export const operations = {
  "flashscore-calendar": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "flashscore-calendar",
    "method": "GET",
    "path": "/flashscore/calendar",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "enum": [
          "tennis-atp",
          "tennis-wta",
          "golf-pga",
          "golf-dp-world",
          "badminton-bwf",
          "motorsport-f1"
        ],
        "in": "query",
        "name": "category",
        "required": true,
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "flashscore-calendar-categories": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "flashscore-calendar-categories",
    "method": "GET",
    "path": "/flashscore/calendar-categories",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "flashscore-competitions": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "flashscore-competitions",
    "method": "GET",
    "path": "/flashscore/competitions",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "enum": [
          "football",
          "tennis",
          "basketball",
          "hockey",
          "golf",
          "formula-1",
          "baseball",
          "snooker",
          "american-football",
          "aussie-rules",
          "badminton",
          "bandy",
          "beach-soccer",
          "beach-volleyball",
          "boxing",
          "cricket",
          "cycling",
          "darts",
          "esports",
          "field-hockey",
          "floorball",
          "futsal",
          "handball",
          "horse-racing",
          "kabaddi",
          "mma",
          "motorsport",
          "netball",
          "pesapallo",
          "rugby-league",
          "rugby-union",
          "table-tennis",
          "volleyball",
          "water-polo",
          "winter-sports"
        ],
        "in": "query",
        "name": "sport",
        "required": true,
        "type": "string"
      },
      {
        "in": "query",
        "name": "day_offset",
        "type": "integer"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "flashscore-match-h2h": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "flashscore-match-h2h",
    "method": "GET",
    "path": "/flashscore/match-h2h",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "id",
        "required": true,
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "flashscore-match-highlights": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "flashscore-match-highlights",
    "method": "GET",
    "path": "/flashscore/match-highlights",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "id",
        "required": true,
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "flashscore-match-info": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "flashscore-match-info",
    "method": "GET",
    "path": "/flashscore/match-info",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "id",
        "required": true,
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "flashscore-match-lineups": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "flashscore-match-lineups",
    "method": "GET",
    "path": "/flashscore/match-lineups",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "id",
        "required": true,
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "flashscore-match-news": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "flashscore-match-news",
    "method": "GET",
    "path": "/flashscore/match-news",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "id",
        "required": true,
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "flashscore-match-standings": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "flashscore-match-standings",
    "method": "GET",
    "path": "/flashscore/match-standings",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "id",
        "required": true,
        "type": "string"
      },
      {
        "enum": [
          "overall",
          "home",
          "away",
          "form_overall",
          "overunder_overall",
          "form_home",
          "form_away",
          "top_scorers",
          "htft_overall",
          "htft_home",
          "htft_away",
          "live_overall",
          "overunder_home",
          "overunder_away"
        ],
        "in": "query",
        "name": "view",
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "flashscore-match-stats": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "flashscore-match-stats",
    "method": "GET",
    "path": "/flashscore/match-stats",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "id",
        "required": true,
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "flashscore-navigation": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "flashscore-navigation",
    "method": "GET",
    "path": "/flashscore/navigation",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "path",
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "flashscore-news": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "flashscore-news",
    "method": "GET",
    "paginatable": true,
    "path": "/flashscore/news",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "enum": [
          "all",
          "football",
          "uefa-nations-league",
          "tennis",
          "features",
          "premier-league",
          "nfl",
          "mlb",
          "nba",
          "nhl",
          "formula-1",
          "champions-league",
          "europa-league",
          "conference-league",
          "darts",
          "snooker",
          "golf",
          "road-cycling",
          "laliga",
          "bundesliga",
          "serie-a",
          "ligue-1",
          "badminton",
          "handball",
          "hockey",
          "basketball",
          "cricket",
          "rugby-union",
          "athletics",
          "baseball",
          "fifa",
          "rugby-league",
          "motorsport",
          "aussie-rules",
          "flashscore-ratings",
          "american-sports",
          "african-football",
          "combat-sports",
          "winter-sports",
          "transfer-news"
        ],
        "in": "query",
        "name": "category",
        "type": "string"
      },
      {
        "in": "query",
        "name": "page",
        "type": "integer"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "flashscore-news-article": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "flashscore-news-article",
    "method": "GET",
    "path": "/flashscore/news-article",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "id",
        "required": true,
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "flashscore-news-categories": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "flashscore-news-categories",
    "method": "GET",
    "path": "/flashscore/news-categories",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "flashscore-ranking-categories": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "flashscore-ranking-categories",
    "method": "GET",
    "path": "/flashscore/ranking-categories",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "flashscore-rankings": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "flashscore-rankings",
    "method": "GET",
    "path": "/flashscore/rankings",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "enum": [
          "fifa",
          "tennis-atp",
          "tennis-wta",
          "tennis-atp-race",
          "tennis-wta-race",
          "tennis-atp-doubles",
          "tennis-wta-doubles",
          "tennis-atp-doubles-race",
          "tennis-wta-doubles-race",
          "badminton-bwf-singles-men",
          "badminton-bwf-singles-women",
          "badminton-bwf-doubles-men",
          "badminton-bwf-doubles-women",
          "badminton-bwf-mixed-doubles",
          "golf-owgr",
          "golf-wwgr",
          "golf-pga-fedexcup",
          "golf-pga-money",
          "golf-dp-world-tour",
          "golf-lpga",
          "golf-asian-tour",
          "golf-japan-tour",
          "golf-sunshine-tour",
          "golf-korn-ferry",
          "golf-champions-tour",
          "darts-world-ranking",
          "snooker-world-ranking",
          "tennis-atp-live",
          "tennis-wta-live",
          "tennis-atp-race-live",
          "tennis-wta-race-live",
          "tennis-atp-doubles-live",
          "tennis-wta-doubles-live",
          "tennis-atp-doubles-race-live",
          "tennis-wta-doubles-race-live"
        ],
        "in": "query",
        "name": "category",
        "required": true,
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "flashscore-scores": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "flashscore-scores",
    "method": "GET",
    "path": "/flashscore/scores",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "enum": [
          "football",
          "tennis",
          "basketball",
          "hockey",
          "golf",
          "formula-1",
          "baseball",
          "snooker",
          "american-football",
          "aussie-rules",
          "badminton",
          "bandy",
          "beach-soccer",
          "beach-volleyball",
          "boxing",
          "cricket",
          "cycling",
          "darts",
          "esports",
          "field-hockey",
          "floorball",
          "futsal",
          "handball",
          "horse-racing",
          "kabaddi",
          "mma",
          "motorsport",
          "netball",
          "pesapallo",
          "rugby-league",
          "rugby-union",
          "table-tennis",
          "volleyball",
          "water-polo",
          "winter-sports"
        ],
        "in": "query",
        "name": "sport",
        "required": true,
        "type": "string"
      },
      {
        "in": "query",
        "name": "day_offset",
        "type": "integer"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "flashscore-search": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "flashscore-search",
    "method": "GET",
    "path": "/flashscore/search",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "q",
        "required": true,
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "flashscore-sports": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "flashscore-sports",
    "method": "GET",
    "path": "/flashscore/sports",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "flashscore-top-search": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "flashscore-top-search",
    "method": "GET",
    "path": "/flashscore/top-search",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "flashscore-tournament-events": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "flashscore-tournament-events",
    "method": "GET",
    "paginatable": true,
    "path": "/flashscore/tournament-events",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "path",
        "required": true,
        "type": "string"
      },
      {
        "in": "query",
        "name": "page",
        "type": "integer"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "flashscore-tournament-seasons": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "flashscore-tournament-seasons",
    "method": "GET",
    "path": "/flashscore/tournament-seasons",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "path",
        "required": true,
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "flashscore-tournament-standings": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "flashscore-tournament-standings",
    "method": "GET",
    "path": "/flashscore/tournament-standings",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "path",
        "required": true,
        "type": "string"
      },
      {
        "enum": [
          "overall",
          "home",
          "away",
          "form_overall",
          "form_home",
          "form_away",
          "overunder_overall",
          "overunder_home",
          "overunder_away",
          "htft_overall",
          "htft_home",
          "htft_away",
          "top_scorers"
        ],
        "in": "query",
        "name": "view",
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "flashscore-tournament-standings-views": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "flashscore-tournament-standings-views",
    "method": "GET",
    "path": "/flashscore/tournament-standings-views",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "path",
        "required": true,
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  }
};

export const groups = {
  "flashscore": {
    "calendar": "flashscore-calendar",
    "calendarCategories": "flashscore-calendar-categories",
    "competitions": "flashscore-competitions",
    "matchH2h": "flashscore-match-h2h",
    "matchHighlights": "flashscore-match-highlights",
    "matchInfo": "flashscore-match-info",
    "matchLineups": "flashscore-match-lineups",
    "matchNews": "flashscore-match-news",
    "matchStandings": "flashscore-match-standings",
    "matchStats": "flashscore-match-stats",
    "navigation": "flashscore-navigation",
    "news": "flashscore-news",
    "newsArticle": "flashscore-news-article",
    "newsCategories": "flashscore-news-categories",
    "rankingCategories": "flashscore-ranking-categories",
    "rankings": "flashscore-rankings",
    "scores": "flashscore-scores",
    "search": "flashscore-search",
    "sports": "flashscore-sports",
    "topSearch": "flashscore-top-search",
    "tournamentEvents": "flashscore-tournament-events",
    "tournamentSeasons": "flashscore-tournament-seasons",
    "tournamentStandings": "flashscore-tournament-standings",
    "tournamentStandingsViews": "flashscore-tournament-standings-views"
  }
};

export const operationCount = 24;

export const OperationIds = Object.freeze({
  "FlashscoreCalendar": "flashscore-calendar",
  "FlashscoreCalendarCategories": "flashscore-calendar-categories",
  "FlashscoreCompetitions": "flashscore-competitions",
  "FlashscoreMatchH2h": "flashscore-match-h2h",
  "FlashscoreMatchHighlights": "flashscore-match-highlights",
  "FlashscoreMatchInfo": "flashscore-match-info",
  "FlashscoreMatchLineups": "flashscore-match-lineups",
  "FlashscoreMatchNews": "flashscore-match-news",
  "FlashscoreMatchStandings": "flashscore-match-standings",
  "FlashscoreMatchStats": "flashscore-match-stats",
  "FlashscoreNavigation": "flashscore-navigation",
  "FlashscoreNews": "flashscore-news",
  "FlashscoreNewsArticle": "flashscore-news-article",
  "FlashscoreNewsCategories": "flashscore-news-categories",
  "FlashscoreRankingCategories": "flashscore-ranking-categories",
  "FlashscoreRankings": "flashscore-rankings",
  "FlashscoreScores": "flashscore-scores",
  "FlashscoreSearch": "flashscore-search",
  "FlashscoreSports": "flashscore-sports",
  "FlashscoreTopSearch": "flashscore-top-search",
  "FlashscoreTournamentEvents": "flashscore-tournament-events",
  "FlashscoreTournamentSeasons": "flashscore-tournament-seasons",
  "FlashscoreTournamentStandings": "flashscore-tournament-standings",
  "FlashscoreTournamentStandingsViews": "flashscore-tournament-standings-views"
});
