// Generated by scripts/generate.py. Do not edit manually.

export type CrawloraResponse<T = unknown> = T;
export type CrawloraBody<T = Record<string, unknown>> = T;

export interface ModelAppResponse {
  "code"?: number;
  "data"?: unknown;
  "msg"?: unknown;
}

export interface ModelFlashscoreTournamentStandingsViewsResponseDoc {
  "path"?: string;
  "source_url"?: string;
  "views"?: Array<string>;
}

export interface ModelFlashscoreTournamentStandingsResponseDoc {
  "data"?: string;
  "path"?: string;
  "source_url"?: string;
  "view"?: string;
}

export interface ModelFlashscoreTournamentSeasonsResponseDoc {
  "code"?: number;
  "data"?: ModelFlashscoreTournamentSeasonsDataDoc;
  "msg"?: string;
}

export interface ModelFlashscoreTournamentSeasonsDataDoc {
  "path"?: string;
  "seasons"?: Array<ModelFlashscoreTournamentSeasonDoc>;
  "source_url"?: string;
}

export interface ModelFlashscoreTournamentSeasonDoc {
  "fixtures_path"?: string;
  "name"?: string;
  "path"?: string;
  "results_path"?: string;
  "season"?: string;
  "winner"?: string;
  "winner_path"?: string;
}

export interface ModelFlashscoreTournamentEventsResponseDoc {
  "code"?: number;
  "data"?: ModelFlashscoreTournamentEventsDataDoc;
  "msg"?: string;
}

export interface ModelFlashscoreTournamentEventsDataDoc {
  "data"?: string;
  "event_count"?: number;
  "page"?: number;
  "path"?: string;
  "section"?: string;
  "source_url"?: string;
  "total_events"?: number;
}

export interface ModelFlashscoreTopSearchResponseDoc {
  "code"?: number;
  "data"?: ModelFlashscoreTopSearchDataDoc;
  "msg"?: string;
}

export interface ModelFlashscoreTopSearchDataDoc {
  "results"?: Array<ModelFlashscoreSearchResultDoc>;
  "source_url"?: string;
}

export interface ModelFlashscoreSearchResultDoc {
  "defaultCountry"?: Record<string, unknown>;
  "defaultTournament"?: Record<string, unknown>;
  "gender"?: ModelFlashscoreSearchNamedIddoc;
  "id"?: string;
  "images"?: Array<ModelFlashscoreSearchImageDoc>;
  "name"?: string;
  "participantTypes"?: Array<ModelFlashscoreSearchNamedIddoc>;
  "sport"?: ModelFlashscoreSearchNamedIddoc;
  "superTemplate"?: Record<string, unknown>;
  "teams"?: Array<Record<string, unknown>>;
  "type"?: ModelFlashscoreSearchNamedIddoc;
  "url"?: string;
}

export interface ModelFlashscoreSearchNamedIddoc {
  "id"?: number;
  "name"?: string;
}

export interface ModelFlashscoreSearchImageDoc {
  "path"?: string;
  "usageId"?: number;
  "variantTypeId"?: number;
}

export interface ModelFlashscoreSportsResponseDoc {
  "code"?: number;
  "data"?: ModelFlashscoreSportsDataDoc;
  "msg"?: string;
}

export interface ModelFlashscoreSportsDataDoc {
  "source_url"?: string;
  "sports"?: Array<ModelFlashscoreSportItemDoc>;
}

export interface ModelFlashscoreSportItemDoc {
  "event_count"?: number;
  "id"?: number;
  "key"?: string;
  "league_count"?: number;
  "name"?: string;
  "path"?: string;
}

export interface ModelFlashscoreSearchResponseDoc {
  "code"?: number;
  "data"?: ModelFlashscoreSearchDataDoc;
  "msg"?: string;
}

export interface ModelFlashscoreSearchDataDoc {
  "query"?: string;
  "results"?: Array<ModelFlashscoreSearchResultDoc>;
  "source_url"?: string;
}

export interface ModelFlashscoreResponseDoc {
  "code"?: number;
  "data"?: ModelFlashscoreSourceDataDoc;
  "msg"?: string;
}

export interface ModelFlashscoreSourceDataDoc {
  "data"?: string;
  "source_url"?: string;
}

export interface ModelFlashscoreRankingResponseDoc {
  "code"?: number;
  "data"?: ModelFlashscoreRankingDataDoc;
  "msg"?: string;
}

export interface ModelFlashscoreRankingDataDoc {
  "category"?: ModelFlashscoreRankingCategoryDoc;
  "pages"?: Array<ModelFlashscoreRankingPageDoc>;
  "source_url"?: string;
}

export interface ModelFlashscoreRankingPageDoc {
  "data"?: string;
  "feed_url"?: string;
  "page"?: number;
  "rows"?: number;
}

export interface ModelFlashscoreRankingCategoryDoc {
  "key"?: string;
  "live"?: boolean;
  "name"?: string;
  "path"?: string;
  "sport"?: string;
}

export interface ModelFlashscoreRankingCategoriesResponseDoc {
  "code"?: number;
  "data"?: ModelFlashscoreRankingCategoriesDataDoc;
  "msg"?: string;
}

export interface ModelFlashscoreRankingCategoriesDataDoc {
  "categories"?: Array<ModelFlashscoreRankingCategoryDoc>;
  "source_url"?: string;
}

export interface ModelFlashscoreNewsCategoriesResponseDoc {
  "code"?: number;
  "data"?: ModelFlashscoreNewsCategoriesDataDoc;
  "msg"?: string;
}

export interface ModelFlashscoreNewsCategoriesDataDoc {
  "categories"?: Array<ModelFlashscoreNewsCategoryDoc>;
  "source_url"?: string;
}

export interface ModelFlashscoreNewsCategoryDoc {
  "key"?: string;
  "name"?: string;
  "path"?: string;
}

export interface ModelFlashscoreNewsArticleResponseDoc {
  "code"?: number;
  "data"?: ModelFlashscoreNewsArticleDataDoc;
  "msg"?: string;
}

export interface ModelFlashscoreNewsArticleDataDoc {
  "article"?: ModelFlashscoreNewsArticleDoc;
  "source_url"?: string;
}

export interface ModelFlashscoreNewsArticleDoc {
  "edited_at"?: number;
  "id"?: string;
  "images"?: Array<ModelFlashscoreNewsImageDoc>;
  "published_at"?: number;
  "slug"?: string;
  "title"?: string;
  "type"?: string;
}

export interface ModelFlashscoreNewsImageDoc {
  "alt_text"?: string;
  "credit"?: string;
  "url"?: string;
  "variant_type_id"?: number;
}

export interface ModelFlashscoreNewsListResponseDoc {
  "code"?: number;
  "data"?: ModelFlashscoreNewsListDataDoc;
  "msg"?: string;
}

export interface ModelFlashscoreNewsListDataDoc {
  "articles"?: Array<ModelFlashscoreNewsPreviewDoc>;
  "category"?: ModelFlashscoreNewsCategoryDoc;
  "has_more"?: boolean;
  "page"?: number;
  "source_url"?: string;
}

export interface ModelFlashscoreNewsPreviewDoc {
  "date"?: string;
  "id"?: string;
  "image_alt"?: string;
  "image_url"?: string;
  "path"?: string;
  "title"?: string;
}

export interface ModelFlashscoreNavigationResponseDoc {
  "code"?: number;
  "data"?: ModelFlashscoreNavigationDataDoc;
  "msg"?: string;
}

export interface ModelFlashscoreNavigationDataDoc {
  "groups"?: Array<ModelFlashscoreNavigationGroupDoc>;
  "path"?: string;
  "source_url"?: string;
  "title"?: string;
}

export interface ModelFlashscoreNavigationGroupDoc {
  "items"?: Array<ModelFlashscoreNavigationItemDoc>;
  "name"?: string;
}

export interface ModelFlashscoreNavigationItemDoc {
  "id"?: number;
  "name"?: string;
  "path"?: string;
  "sport_id"?: number;
}

export interface ModelFlashscoreMatchNewsResponseDoc {
  "code"?: number;
  "data"?: ModelFlashscoreMatchNewsDataDoc;
  "msg"?: string;
}

export interface ModelFlashscoreMatchNewsDataDoc {
  "layout_id"?: number;
  "match_id"?: string;
  "name"?: string;
  "sections"?: Array<ModelFlashscoreMatchNewsSectionDoc>;
  "source_url"?: string;
}

export interface ModelFlashscoreMatchNewsSectionDoc {
  "articles"?: Array<ModelFlashscoreMatchNewsArticleRefDoc>;
  "id"?: number;
  "name"?: string;
}

export interface ModelFlashscoreMatchNewsArticleRefDoc {
  "article"?: ModelFlashscoreMatchNewsArticleSortKeyDoc;
  "id"?: string;
}

export interface ModelFlashscoreMatchNewsArticleSortKeyDoc {
  "sort_key"?: number;
}

export interface ModelFlashscoreCompetitionsResponseDoc {
  "code"?: number;
  "data"?: ModelFlashscoreCompetitionsDataDoc;
  "msg"?: string;
}

export interface ModelFlashscoreCompetitionsDataDoc {
  "competitions"?: Array<ModelFlashscoreCompetitionDoc>;
  "day_offset"?: number;
  "source_url"?: string;
  "sport"?: string;
}

export interface ModelFlashscoreCompetitionDoc {
  "event_count"?: number;
  "id"?: string;
  "name"?: string;
  "path"?: string;
  "region"?: string;
}

export interface ModelFlashscoreCalendarCategoriesResponseDoc {
  "code"?: number;
  "data"?: ModelFlashscoreCalendarCategoriesDataDoc;
  "msg"?: string;
}

export interface ModelFlashscoreCalendarCategoriesDataDoc {
  "categories"?: Array<ModelFlashscoreCalendarCategoryDoc>;
  "source_url"?: string;
}

export interface ModelFlashscoreCalendarCategoryDoc {
  "key"?: string;
  "name"?: string;
  "path"?: string;
  "sport"?: string;
}

export interface ModelFlashscoreCalendarResponseDoc {
  "code"?: number;
  "data"?: ModelFlashscoreCalendarDataDoc;
  "msg"?: string;
}

export interface ModelFlashscoreCalendarDataDoc {
  "category"?: ModelFlashscoreCalendarCategoryDoc;
  "events"?: Array<ModelFlashscoreCalendarEventDoc>;
  "source_url"?: string;
  "year"?: number;
}

export interface ModelFlashscoreCalendarEventDoc {
  "date"?: string;
  "month"?: string;
  "name"?: string;
  "path"?: string;
  "winner"?: string;
}

export type FlashscoreCalendarResponse = CrawloraResponse<ModelFlashscoreCalendarResponseDoc>;
export interface FlashscoreCalendarParams {
  "category": "tennis-atp" | "tennis-wta" | "golf-pga" | "golf-dp-world" | "badminton-bwf" | "motorsport-f1";
}

export type FlashscoreCalendarCategoriesResponse = CrawloraResponse<ModelFlashscoreCalendarCategoriesResponseDoc>;
export interface FlashscoreCalendarCategoriesParams {
}

export type FlashscoreCompetitionsResponse = CrawloraResponse<ModelFlashscoreCompetitionsResponseDoc>;
export interface FlashscoreCompetitionsParams {
  "sport": "football" | "tennis" | "basketball" | "hockey" | "golf" | "formula-1" | "baseball" | "snooker" | "american-football" | "aussie-rules" | "badminton" | "bandy" | "beach-soccer" | "beach-volleyball" | "boxing" | "cricket" | "cycling" | "darts" | "esports" | "field-hockey" | "floorball" | "futsal" | "handball" | "horse-racing" | "kabaddi" | "mma" | "motorsport" | "netball" | "pesapallo" | "rugby-league" | "rugby-union" | "table-tennis" | "volleyball" | "water-polo" | "winter-sports";
  "day_offset"?: number;
}

export type FlashscoreMatchH2hResponse = CrawloraResponse<ModelFlashscoreResponseDoc>;
export interface FlashscoreMatchH2hParams {
  "id": string;
}

export type FlashscoreMatchHighlightsResponse = CrawloraResponse<ModelFlashscoreResponseDoc>;
export interface FlashscoreMatchHighlightsParams {
  "id": string;
}

export type FlashscoreMatchInfoResponse = CrawloraResponse<ModelFlashscoreResponseDoc>;
export interface FlashscoreMatchInfoParams {
  "id": string;
}

export type FlashscoreMatchLineupsResponse = CrawloraResponse<ModelFlashscoreResponseDoc>;
export interface FlashscoreMatchLineupsParams {
  "id": string;
}

export type FlashscoreMatchNewsResponse = CrawloraResponse<ModelFlashscoreMatchNewsResponseDoc>;
export interface FlashscoreMatchNewsParams {
  "id": string;
}

export type FlashscoreMatchStandingsResponse = CrawloraResponse<ModelFlashscoreResponseDoc>;
export interface FlashscoreMatchStandingsParams {
  "id": string;
  "view"?: "overall" | "home" | "away" | "form_overall" | "overunder_overall" | "form_home" | "form_away" | "top_scorers" | "htft_overall" | "htft_home" | "htft_away" | "live_overall" | "overunder_home" | "overunder_away";
}

export type FlashscoreMatchStatsResponse = CrawloraResponse<ModelFlashscoreResponseDoc>;
export interface FlashscoreMatchStatsParams {
  "id": string;
}

export type FlashscoreNavigationResponse = CrawloraResponse<ModelFlashscoreNavigationResponseDoc>;
export interface FlashscoreNavigationParams {
  "path"?: string;
}

export type FlashscoreNewsResponse = CrawloraResponse<ModelFlashscoreNewsListResponseDoc>;
export interface FlashscoreNewsParams {
  "category"?: "all" | "football" | "uefa-nations-league" | "tennis" | "features" | "premier-league" | "nfl" | "mlb" | "nba" | "nhl" | "formula-1" | "champions-league" | "europa-league" | "conference-league" | "darts" | "snooker" | "golf" | "road-cycling" | "laliga" | "bundesliga" | "serie-a" | "ligue-1" | "badminton" | "handball" | "hockey" | "basketball" | "cricket" | "rugby-union" | "athletics" | "baseball" | "fifa" | "rugby-league" | "motorsport" | "aussie-rules" | "flashscore-ratings" | "american-sports" | "african-football" | "combat-sports" | "winter-sports" | "transfer-news";
  "page"?: number;
}

export type FlashscoreNewsArticleResponse = CrawloraResponse<ModelFlashscoreNewsArticleResponseDoc>;
export interface FlashscoreNewsArticleParams {
  "id": string;
}

export type FlashscoreNewsCategoriesResponse = CrawloraResponse<ModelFlashscoreNewsCategoriesResponseDoc>;
export interface FlashscoreNewsCategoriesParams {
}

export type FlashscoreRankingCategoriesResponse = CrawloraResponse<ModelFlashscoreRankingCategoriesResponseDoc>;
export interface FlashscoreRankingCategoriesParams {
}

export type FlashscoreRankingsResponse = CrawloraResponse<ModelFlashscoreRankingResponseDoc>;
export interface FlashscoreRankingsParams {
  "category": "fifa" | "tennis-atp" | "tennis-wta" | "tennis-atp-race" | "tennis-wta-race" | "tennis-atp-doubles" | "tennis-wta-doubles" | "tennis-atp-doubles-race" | "tennis-wta-doubles-race" | "badminton-bwf-singles-men" | "badminton-bwf-singles-women" | "badminton-bwf-doubles-men" | "badminton-bwf-doubles-women" | "badminton-bwf-mixed-doubles" | "golf-owgr" | "golf-wwgr" | "golf-pga-fedexcup" | "golf-pga-money" | "golf-dp-world-tour" | "golf-lpga" | "golf-asian-tour" | "golf-japan-tour" | "golf-sunshine-tour" | "golf-korn-ferry" | "golf-champions-tour" | "darts-world-ranking" | "snooker-world-ranking" | "tennis-atp-live" | "tennis-wta-live" | "tennis-atp-race-live" | "tennis-wta-race-live" | "tennis-atp-doubles-live" | "tennis-wta-doubles-live" | "tennis-atp-doubles-race-live" | "tennis-wta-doubles-race-live";
}

export type FlashscoreScoresResponse = CrawloraResponse<ModelFlashscoreResponseDoc>;
export interface FlashscoreScoresParams {
  "sport": "football" | "tennis" | "basketball" | "hockey" | "golf" | "formula-1" | "baseball" | "snooker" | "american-football" | "aussie-rules" | "badminton" | "bandy" | "beach-soccer" | "beach-volleyball" | "boxing" | "cricket" | "cycling" | "darts" | "esports" | "field-hockey" | "floorball" | "futsal" | "handball" | "horse-racing" | "kabaddi" | "mma" | "motorsport" | "netball" | "pesapallo" | "rugby-league" | "rugby-union" | "table-tennis" | "volleyball" | "water-polo" | "winter-sports";
  "day_offset"?: number;
}

export type FlashscoreSearchResponse = CrawloraResponse<ModelFlashscoreSearchResponseDoc>;
export interface FlashscoreSearchParams {
  "q": string;
}

export type FlashscoreSportsResponse = CrawloraResponse<ModelFlashscoreSportsResponseDoc>;
export interface FlashscoreSportsParams {
}

export type FlashscoreTopSearchResponse = CrawloraResponse<ModelFlashscoreTopSearchResponseDoc>;
export interface FlashscoreTopSearchParams {
}

export type FlashscoreTournamentEventsResponse = CrawloraResponse<ModelFlashscoreTournamentEventsResponseDoc>;
export interface FlashscoreTournamentEventsParams {
  "path": string;
  "page"?: number;
}

export type FlashscoreTournamentSeasonsResponse = CrawloraResponse<ModelFlashscoreTournamentSeasonsResponseDoc>;
export interface FlashscoreTournamentSeasonsParams {
  "path": string;
}

export type FlashscoreTournamentStandingsResponse = CrawloraResponse<ModelFlashscoreTournamentStandingsResponseDoc>;
export interface FlashscoreTournamentStandingsParams {
  "path": string;
  "view"?: "overall" | "home" | "away" | "form_overall" | "form_home" | "form_away" | "overunder_overall" | "overunder_home" | "overunder_away" | "htft_overall" | "htft_home" | "htft_away" | "top_scorers";
}

export type FlashscoreTournamentStandingsViewsResponse = CrawloraResponse<ModelFlashscoreTournamentStandingsViewsResponseDoc>;
export interface FlashscoreTournamentStandingsViewsParams {
  "path": string;
}

export interface FlashscoreService {
  calendar<T = FlashscoreCalendarResponse>(params: FlashscoreCalendarParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  calendarCategories<T = FlashscoreCalendarCategoriesResponse>(params?: FlashscoreCalendarCategoriesParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  competitions<T = FlashscoreCompetitionsResponse>(params: FlashscoreCompetitionsParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  matchH2h<T = FlashscoreMatchH2hResponse>(params: FlashscoreMatchH2hParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  matchHighlights<T = FlashscoreMatchHighlightsResponse>(params: FlashscoreMatchHighlightsParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  matchInfo<T = FlashscoreMatchInfoResponse>(params: FlashscoreMatchInfoParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  matchLineups<T = FlashscoreMatchLineupsResponse>(params: FlashscoreMatchLineupsParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  matchNews<T = FlashscoreMatchNewsResponse>(params: FlashscoreMatchNewsParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  matchStandings<T = FlashscoreMatchStandingsResponse>(params: FlashscoreMatchStandingsParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  matchStats<T = FlashscoreMatchStatsResponse>(params: FlashscoreMatchStatsParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  navigation<T = FlashscoreNavigationResponse>(params?: FlashscoreNavigationParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  news<T = FlashscoreNewsResponse>(params?: FlashscoreNewsParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  newsArticle<T = FlashscoreNewsArticleResponse>(params: FlashscoreNewsArticleParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  newsCategories<T = FlashscoreNewsCategoriesResponse>(params?: FlashscoreNewsCategoriesParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  rankingCategories<T = FlashscoreRankingCategoriesResponse>(params?: FlashscoreRankingCategoriesParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  rankings<T = FlashscoreRankingsResponse>(params: FlashscoreRankingsParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  scores<T = FlashscoreScoresResponse>(params: FlashscoreScoresParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  search<T = FlashscoreSearchResponse>(params: FlashscoreSearchParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  sports<T = FlashscoreSportsResponse>(params?: FlashscoreSportsParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  topSearch<T = FlashscoreTopSearchResponse>(params?: FlashscoreTopSearchParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  tournamentEvents<T = FlashscoreTournamentEventsResponse>(params: FlashscoreTournamentEventsParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  tournamentSeasons<T = FlashscoreTournamentSeasonsResponse>(params: FlashscoreTournamentSeasonsParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  tournamentStandings<T = FlashscoreTournamentStandingsResponse>(params: FlashscoreTournamentStandingsParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  tournamentStandingsViews<T = FlashscoreTournamentStandingsViewsResponse>(params: FlashscoreTournamentStandingsViewsParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
}

export interface CrawloraGeneratedGroups {
  flashscore: FlashscoreService;
}

export interface OperationParamsMap {
  "flashscore-calendar": FlashscoreCalendarParams;
  "flashscore-calendar-categories": FlashscoreCalendarCategoriesParams;
  "flashscore-competitions": FlashscoreCompetitionsParams;
  "flashscore-match-h2h": FlashscoreMatchH2hParams;
  "flashscore-match-highlights": FlashscoreMatchHighlightsParams;
  "flashscore-match-info": FlashscoreMatchInfoParams;
  "flashscore-match-lineups": FlashscoreMatchLineupsParams;
  "flashscore-match-news": FlashscoreMatchNewsParams;
  "flashscore-match-standings": FlashscoreMatchStandingsParams;
  "flashscore-match-stats": FlashscoreMatchStatsParams;
  "flashscore-navigation": FlashscoreNavigationParams;
  "flashscore-news": FlashscoreNewsParams;
  "flashscore-news-article": FlashscoreNewsArticleParams;
  "flashscore-news-categories": FlashscoreNewsCategoriesParams;
  "flashscore-ranking-categories": FlashscoreRankingCategoriesParams;
  "flashscore-rankings": FlashscoreRankingsParams;
  "flashscore-scores": FlashscoreScoresParams;
  "flashscore-search": FlashscoreSearchParams;
  "flashscore-sports": FlashscoreSportsParams;
  "flashscore-top-search": FlashscoreTopSearchParams;
  "flashscore-tournament-events": FlashscoreTournamentEventsParams;
  "flashscore-tournament-seasons": FlashscoreTournamentSeasonsParams;
  "flashscore-tournament-standings": FlashscoreTournamentStandingsParams;
  "flashscore-tournament-standings-views": FlashscoreTournamentStandingsViewsParams;
}

export interface OperationResponseMap {
  "flashscore-calendar": FlashscoreCalendarResponse;
  "flashscore-calendar-categories": FlashscoreCalendarCategoriesResponse;
  "flashscore-competitions": FlashscoreCompetitionsResponse;
  "flashscore-match-h2h": FlashscoreMatchH2hResponse;
  "flashscore-match-highlights": FlashscoreMatchHighlightsResponse;
  "flashscore-match-info": FlashscoreMatchInfoResponse;
  "flashscore-match-lineups": FlashscoreMatchLineupsResponse;
  "flashscore-match-news": FlashscoreMatchNewsResponse;
  "flashscore-match-standings": FlashscoreMatchStandingsResponse;
  "flashscore-match-stats": FlashscoreMatchStatsResponse;
  "flashscore-navigation": FlashscoreNavigationResponse;
  "flashscore-news": FlashscoreNewsResponse;
  "flashscore-news-article": FlashscoreNewsArticleResponse;
  "flashscore-news-categories": FlashscoreNewsCategoriesResponse;
  "flashscore-ranking-categories": FlashscoreRankingCategoriesResponse;
  "flashscore-rankings": FlashscoreRankingsResponse;
  "flashscore-scores": FlashscoreScoresResponse;
  "flashscore-search": FlashscoreSearchResponse;
  "flashscore-sports": FlashscoreSportsResponse;
  "flashscore-top-search": FlashscoreTopSearchResponse;
  "flashscore-tournament-events": FlashscoreTournamentEventsResponse;
  "flashscore-tournament-seasons": FlashscoreTournamentSeasonsResponse;
  "flashscore-tournament-standings": FlashscoreTournamentStandingsResponse;
  "flashscore-tournament-standings-views": FlashscoreTournamentStandingsViewsResponse;
}

export interface OperationRequiredParamsMap {
  "flashscore-calendar": true;
  "flashscore-calendar-categories": false;
  "flashscore-competitions": true;
  "flashscore-match-h2h": true;
  "flashscore-match-highlights": true;
  "flashscore-match-info": true;
  "flashscore-match-lineups": true;
  "flashscore-match-news": true;
  "flashscore-match-standings": true;
  "flashscore-match-stats": true;
  "flashscore-navigation": false;
  "flashscore-news": false;
  "flashscore-news-article": true;
  "flashscore-news-categories": false;
  "flashscore-ranking-categories": false;
  "flashscore-rankings": true;
  "flashscore-scores": true;
  "flashscore-search": true;
  "flashscore-sports": false;
  "flashscore-top-search": false;
  "flashscore-tournament-events": true;
  "flashscore-tournament-seasons": true;
  "flashscore-tournament-standings": true;
  "flashscore-tournament-standings-views": true;
}

export type OperationId = keyof OperationParamsMap;

export type OperationRequestArgs<I extends OperationId> =
  OperationRequiredParamsMap[I] extends true
    ? [params: OperationParamsMap[I], options?: import('./index.js').CrawloraRequestOptions]
    : [params?: OperationParamsMap[I], options?: import('./index.js').CrawloraRequestOptions];

export type OperationIdLiteral =
  | "flashscore-calendar"
  | "flashscore-calendar-categories"
  | "flashscore-competitions"
  | "flashscore-match-h2h"
  | "flashscore-match-highlights"
  | "flashscore-match-info"
  | "flashscore-match-lineups"
  | "flashscore-match-news"
  | "flashscore-match-standings"
  | "flashscore-match-stats"
  | "flashscore-navigation"
  | "flashscore-news"
  | "flashscore-news-article"
  | "flashscore-news-categories"
  | "flashscore-ranking-categories"
  | "flashscore-rankings"
  | "flashscore-scores"
  | "flashscore-search"
  | "flashscore-sports"
  | "flashscore-top-search"
  | "flashscore-tournament-events"
  | "flashscore-tournament-seasons"
  | "flashscore-tournament-standings"
  | "flashscore-tournament-standings-views";

export declare const OperationIds: Readonly<{
  FlashscoreCalendar: "flashscore-calendar";
  FlashscoreCalendarCategories: "flashscore-calendar-categories";
  FlashscoreCompetitions: "flashscore-competitions";
  FlashscoreMatchH2h: "flashscore-match-h2h";
  FlashscoreMatchHighlights: "flashscore-match-highlights";
  FlashscoreMatchInfo: "flashscore-match-info";
  FlashscoreMatchLineups: "flashscore-match-lineups";
  FlashscoreMatchNews: "flashscore-match-news";
  FlashscoreMatchStandings: "flashscore-match-standings";
  FlashscoreMatchStats: "flashscore-match-stats";
  FlashscoreNavigation: "flashscore-navigation";
  FlashscoreNews: "flashscore-news";
  FlashscoreNewsArticle: "flashscore-news-article";
  FlashscoreNewsCategories: "flashscore-news-categories";
  FlashscoreRankingCategories: "flashscore-ranking-categories";
  FlashscoreRankings: "flashscore-rankings";
  FlashscoreScores: "flashscore-scores";
  FlashscoreSearch: "flashscore-search";
  FlashscoreSports: "flashscore-sports";
  FlashscoreTopSearch: "flashscore-top-search";
  FlashscoreTournamentEvents: "flashscore-tournament-events";
  FlashscoreTournamentSeasons: "flashscore-tournament-seasons";
  FlashscoreTournamentStandings: "flashscore-tournament-standings";
  FlashscoreTournamentStandingsViews: "flashscore-tournament-standings-views";
}>;
