// Generated by scripts/generate.py. Do not edit manually.

export type CrawloraResponse<T = unknown> = T;
export type CrawloraBody<T = Record<string, unknown>> = T;

export interface ModelAppResponse {
  "code"?: number;
  "data"?: unknown;
  "msg"?: unknown;
}

export interface ModelFlashscoreTournamentStandingsViewsResponseDoc {
  "path"?: string;
  "source_url"?: string;
  "views"?: Array<string>;
}

export interface ModelFlashscoreTournamentStandingsResponseDoc {
  "data"?: string;
  "path"?: string;
  "source_url"?: string;
  "view"?: string;
}

export interface ModelFlashscoreTournamentSeasonsResponseDoc {
  "code"?: number;
  "data"?: ModelFlashscoreTournamentSeasonsDataDoc;
  "msg"?: string;
}

export interface ModelFlashscoreTournamentSeasonsDataDoc {
  "path"?: string;
  "seasons"?: Array<ModelFlashscoreTournamentSeasonDoc>;
  "source_url"?: string;
}

export interface ModelFlashscoreTournamentSeasonDoc {
  "fixtures_path"?: string;
  "name"?: string;
  "path"?: string;
  "results_path"?: string;
  "season"?: string;
  "winner"?: string;
  "winner_path"?: string;
  "winners"?: Array<ModelFlashscoreTournamentSeasonWinnerDoc>;
}

export interface ModelFlashscoreTournamentSeasonWinnerDoc {
  "name"?: string;
  "path"?: string;
}

export interface ModelFlashscoreTournamentOutrightOddsResponse {
  "bookmakers"?: Array<ModelFlashscoreOddsBookmaker>;
  "geo"?: string;
  "has_more"?: boolean;
  "participants"?: Array<ModelFlashscoreOutrightParticipant>;
  "source_url"?: string;
  "subdivision"?: string;
  "tournament_id"?: string;
}

export interface ModelFlashscoreOutrightParticipant {
  "id"?: string;
  "name"?: string;
  "offers"?: Array<ModelFlashscoreOutrightOffer>;
}

export interface ModelFlashscoreOutrightOffer {
  "active"?: boolean;
  "best"?: boolean;
  "bookmaker_id"?: number;
  "change"?: "UP" | "DOWN";
  "odds"?: number;
}

export interface ModelFlashscoreOddsBookmaker {
  "id"?: number;
  "name"?: string;
}

export interface ModelFlashscoreTournamentEventsResponseDoc {
  "code"?: number;
  "data"?: ModelFlashscoreTournamentEventsDataDoc;
  "msg"?: string;
}

export interface ModelFlashscoreTournamentEventsDataDoc {
  "data"?: string;
  "event_count"?: number;
  "page"?: number;
  "path"?: string;
  "section"?: string;
  "source_url"?: string;
  "total_events"?: number;
}

export interface ModelFlashscoreTournamentArchiveSeasonsResponse {
  "league_key"?: string;
  "season_count"?: number;
  "seasons"?: Array<ModelFlashscoreArchiveSeason>;
  "source_url"?: string;
  "stage"?: ModelFlashscoreArchiveStage;
  "stage_id"?: string;
  "tournament_template_id"?: string;
}

export interface ModelFlashscoreArchiveStage {
  "country"?: string;
  "end_estimated"?: string;
  "group"?: string;
  "id"?: string;
  "is_final"?: boolean;
  "name"?: string;
  "start_estimated"?: string;
  "tabs"?: Array<ModelFlashscoreArchiveTab>;
  "tournament"?: string;
  "type_id"?: number;
}

export interface ModelFlashscoreArchiveTab {
  "id"?: "SU" | "OD" | "TA" | "RE" | "FI" | "DR" | "NF";
  "name"?: string;
}

export interface ModelFlashscoreArchiveSeason {
  "end_year"?: string;
  "is_current"?: boolean;
  "is_requested"?: boolean;
  "season"?: string;
  "stage_ids"?: Array<string>;
  "start_year"?: string;
  "tournament_id"?: string;
  "winners"?: Array<ModelFlashscoreArchiveWinner>;
}

export interface ModelFlashscoreArchiveWinner {
  "id"?: string;
  "name"?: string;
  "slug"?: string;
}

export interface ModelFlashscoreTopSearchResponseDoc {
  "code"?: number;
  "data"?: ModelFlashscoreTopSearchDataDoc;
  "msg"?: string;
}

export interface ModelFlashscoreTopSearchDataDoc {
  "results"?: Array<ModelFlashscoreSearchResultDoc>;
  "source_url"?: string;
}

export interface ModelFlashscoreSearchResultDoc {
  "defaultCountry"?: Record<string, unknown>;
  "defaultTournament"?: Record<string, unknown>;
  "gender"?: ModelFlashscoreSearchNamedIddoc;
  "id"?: string;
  "images"?: Array<ModelFlashscoreSearchImageDoc>;
  "name"?: string;
  "participantTypes"?: Array<ModelFlashscoreSearchNamedIddoc>;
  "sport"?: ModelFlashscoreSearchNamedIddoc;
  "superTemplate"?: Record<string, unknown>;
  "teams"?: Array<Record<string, unknown>>;
  "type"?: ModelFlashscoreSearchNamedIddoc;
  "url"?: string;
}

export interface ModelFlashscoreSearchNamedIddoc {
  "id"?: number;
  "name"?: string;
}

export interface ModelFlashscoreSearchImageDoc {
  "path"?: string;
  "usageId"?: number;
  "variantTypeId"?: number;
}

export interface ModelFlashscoreTeamTransfersResponse {
  "page"?: number;
  "source_url"?: string;
  "team_id"?: string;
  "team_name"?: string;
  "transfer_count"?: number;
  "transfers"?: Array<ModelFlashscoreTeamTransfer>;
  "type"?: string;
}

export interface ModelFlashscoreTeamTransfer {
  "date"?: string;
  "direction"?: string;
  "fee"?: string;
  "from"?: ModelFlashscoreTransferTeam;
  "player"?: ModelFlashscoreTransferPlayer;
  "to"?: ModelFlashscoreTransferTeam;
  "type"?: string;
}

export interface ModelFlashscoreTransferTeam {
  "id"?: string;
  "logo_url"?: string;
  "name"?: string;
  "path"?: string;
  "slug"?: string;
}

export interface ModelFlashscoreTransferPlayer {
  "country"?: string;
  "id"?: string;
  "name"?: string;
  "path"?: string;
  "slug"?: string;
}

export interface ModelFlashscoreTeamSquadResponse {
  "groups"?: Array<ModelFlashscoreSquadGroup>;
  "scope"?: ModelFlashscoreSquadScope;
  "scopes"?: Array<ModelFlashscoreSquadScope>;
  "source_url"?: string;
  "team"?: ModelFlashscoreTeamProfile;
}

export interface ModelFlashscoreTeamProfile {
  "country"?: string;
  "country_id"?: number;
  "full_name"?: string;
  "id"?: string;
  "logo_url"?: string;
  "name"?: string;
  "path"?: string;
  "slug"?: string;
  "sport"?: string;
  "sport_id"?: number;
  "url"?: string;
}

export interface ModelFlashscoreSquadScope {
  "key"?: string;
  "name"?: string;
}

export interface ModelFlashscoreSquadGroup {
  "columns"?: Array<ModelFlashscoreSquadColumn>;
  "name"?: string;
  "players"?: Array<ModelFlashscoreSquadPlayer>;
}

export interface ModelFlashscoreSquadPlayer {
  "absence"?: string;
  "age"?: number;
  "club"?: string;
  "country"?: string;
  "jersey_number"?: string;
  "name"?: string;
  "path"?: string;
  "player_id"?: string;
  "slug"?: string;
  "stats"?: Record<string, unknown>;
}

export interface ModelFlashscoreSquadColumn {
  "key"?: string;
  "label"?: string;
}

export interface ModelFlashscoreTeamEventsResponse {
  "event_count"?: number;
  "events"?: Array<ModelFlashscoreTeamEvent>;
  "page"?: number;
  "section"?: string;
  "source_url"?: string;
  "team_id"?: string;
  "team_name"?: string;
}

export interface ModelFlashscoreTeamEvent {
  "away"?: ModelFlashscoreEventSide;
  "away_score"?: number;
  "competition"?: ModelFlashscoreEventCompetition;
  "home"?: ModelFlashscoreEventSide;
  "home_score"?: number;
  "id"?: string;
  "stage"?: string;
  "stage_code"?: number;
  "start_time"?: number;
  "start_time_iso"?: string;
  "status_code"?: number;
}

export interface ModelFlashscoreEventSide {
  "id"?: string;
  "logo_url"?: string;
  "name"?: string;
  "short_name"?: string;
  "slug"?: string;
}

export interface ModelFlashscoreEventCompetition {
  "country"?: string;
  "full_name"?: string;
  "id"?: string;
  "name"?: string;
  "path"?: string;
  "stage_id"?: string;
  "tournament_id"?: string;
  "tournament_stage_id"?: string;
}

export interface ModelFlashscoreTeamOutrightOddsResponse {
  "bookmakers"?: Array<ModelFlashscoreOddsBookmaker>;
  "geo"?: string;
  "has_more"?: boolean;
  "source_url"?: string;
  "subdivision"?: string;
  "team_id"?: string;
  "team_name"?: string;
  "tournaments"?: Array<ModelFlashscoreOutrightTournament>;
}

export interface ModelFlashscoreOutrightTournament {
  "id"?: string;
  "name"?: string;
  "offers"?: Array<ModelFlashscoreOutrightOffer>;
}

export interface ModelFlashscoreTeamNewsResponse {
  "item_count"?: number;
  "items"?: Array<ModelFlashscoreTeamNewsItem>;
  "source_url"?: string;
  "team_id"?: string;
  "team_name"?: string;
}

export interface ModelFlashscoreTeamNewsItem {
  "id"?: string;
  "image_url"?: string;
  "link"?: string;
  "published_at"?: number;
  "published_at_iso"?: string;
  "publisher"?: string;
  "title"?: string;
}

export interface ModelFlashscoreTeamResponse {
  "competitions"?: Array<ModelFlashscoreTeamCompetition>;
  "page_url"?: string;
  "source_url"?: string;
  "team"?: ModelFlashscoreTeamProfile;
  "venue"?: ModelFlashscoreTeamVenue;
}

export interface ModelFlashscoreTeamVenue {
  "capacity"?: number;
  "city"?: string;
  "stadium"?: string;
}

export interface ModelFlashscoreTeamCompetition {
  "country"?: string;
  "full_name"?: string;
  "name"?: string;
  "path"?: string;
}

export interface ModelFlashscoreSportsResponseDoc {
  "code"?: number;
  "data"?: ModelFlashscoreSportsDataDoc;
  "msg"?: string;
}

export interface ModelFlashscoreSportsDataDoc {
  "source_url"?: string;
  "sports"?: Array<ModelFlashscoreSportItemDoc>;
}

export interface ModelFlashscoreSportItemDoc {
  "event_count"?: number;
  "id"?: number;
  "key"?: string;
  "league_count"?: number;
  "name"?: string;
  "path"?: string;
}

export interface ModelFlashscoreSearchResponseDoc {
  "code"?: number;
  "data"?: ModelFlashscoreSearchDataDoc;
  "msg"?: string;
}

export interface ModelFlashscoreSearchDataDoc {
  "query"?: string;
  "results"?: Array<ModelFlashscoreSearchResultDoc>;
  "source_url"?: string;
}

export interface ModelFlashscoreResponseDoc {
  "code"?: number;
  "data"?: ModelFlashscoreSourceDataDoc;
  "msg"?: string;
}

export interface ModelFlashscoreSourceDataDoc {
  "data"?: string;
  "source_url"?: string;
}

export interface ModelFlashscoreRankingResponseDoc {
  "code"?: number;
  "data"?: ModelFlashscoreRankingDataDoc;
  "msg"?: string;
}

export interface ModelFlashscoreRankingDataDoc {
  "category"?: ModelFlashscoreRankingCategoryDoc;
  "pages"?: Array<ModelFlashscoreRankingPageDoc>;
  "source_url"?: string;
}

export interface ModelFlashscoreRankingPageDoc {
  "data"?: string;
  "feed_url"?: string;
  "page"?: number;
  "rows"?: number;
}

export interface ModelFlashscoreRankingCategoryDoc {
  "key"?: string;
  "live"?: boolean;
  "name"?: string;
  "path"?: string;
  "sport"?: string;
}

export interface ModelFlashscoreRankingCategoriesResponseDoc {
  "code"?: number;
  "data"?: ModelFlashscoreRankingCategoriesDataDoc;
  "msg"?: string;
}

export interface ModelFlashscoreRankingCategoriesDataDoc {
  "categories"?: Array<ModelFlashscoreRankingCategoryDoc>;
  "source_url"?: string;
}

export interface ModelFlashscorePlayerTransfersResponse {
  "page_url"?: string;
  "player"?: ModelFlashscorePlayerProfile;
  "source_url"?: string;
  "transfer_count"?: number;
  "transfers"?: Array<ModelFlashscorePlayerTransfer>;
}

export interface ModelFlashscorePlayerTransfer {
  "date"?: string;
  "fee"?: string;
  "from"?: ModelFlashscoreTransferTeam;
  "to"?: ModelFlashscoreTransferTeam;
  "type"?: string;
}

export interface ModelFlashscorePlayerProfile {
  "birth_date"?: string;
  "country"?: string;
  "country_id"?: number;
  "full_name"?: string;
  "id"?: string;
  "name"?: string;
  "path"?: string;
  "photo_url"?: string;
  "ranking"?: string;
  "slug"?: string;
  "sport"?: string;
  "sport_id"?: number;
  "team"?: ModelFlashscorePlayerTeam;
  "url"?: string;
}

export interface ModelFlashscorePlayerTeam {
  "id"?: string;
  "logo_url"?: string;
  "name"?: string;
  "path"?: string;
  "slug"?: string;
}

export interface ModelFlashscorePlayerEventsResponse {
  "event_count"?: number;
  "events"?: Array<ModelFlashscoreTeamEvent>;
  "page"?: number;
  "player_id"?: string;
  "player_name"?: string;
  "section"?: string;
  "source_url"?: string;
}

export interface ModelFlashscorePlayerNewsResponse {
  "item_count"?: number;
  "items"?: Array<ModelFlashscoreTeamNewsItem>;
  "player_id"?: string;
  "player_name"?: string;
  "source_url"?: string;
}

export interface ModelFlashscorePlayerMatchLogResponse {
  "has_more"?: boolean;
  "page"?: number;
  "player"?: ModelFlashscorePlayerProfile;
  "row_count"?: number;
  "rows"?: Array<ModelFlashscorePlayerMatchLogRow>;
  "source_url"?: string;
}

export interface ModelFlashscorePlayerMatchLogRow {
  "absence"?: ModelFlashscorePlayerMatchLogAbsence;
  "away"?: ModelFlashscorePlayerMatchLogSide;
  "date"?: string;
  "date_text"?: string;
  "event_id"?: string;
  "home"?: ModelFlashscorePlayerMatchLogSide;
  "rating"?: number;
  "rating_rank"?: number;
  "result"?: "win" | "draw" | "loss";
  "stage"?: "finished" | "finished_after_extra_time" | "finished_after_penalties" | "other";
  "stage_code"?: number;
  "stats"?: Array<ModelFlashscorePlayerMatchLogStat>;
  "stats_available"?: boolean;
  "tournament"?: ModelFlashscorePlayerMatchLogTournament;
}

export interface ModelFlashscorePlayerMatchLogTournament {
  "country"?: string;
  "country_id"?: number;
  "name"?: string;
  "path"?: string;
  "season"?: string;
  "short_code"?: string;
}

export interface ModelFlashscorePlayerMatchLogStat {
  "id"?: number;
  "key"?: string;
  "label"?: string;
  "value"?: string;
}

export interface ModelFlashscorePlayerMatchLogSide {
  "full_time_score"?: number;
  "id"?: string;
  "logo_url"?: string;
  "name"?: string;
  "penalties_score"?: number;
  "score"?: number;
  "score_after_extra_time"?: number;
  "short_name"?: string;
  "slug"?: string;
}

export interface ModelFlashscorePlayerMatchLogAbsence {
  "category"?: string;
  "detail"?: string;
}

export interface ModelFlashscorePlayerInjuriesResponse {
  "injuries"?: Array<ModelFlashscorePlayerInjury>;
  "injury_count"?: number;
  "page_url"?: string;
  "player"?: ModelFlashscorePlayerProfile;
  "source_url"?: string;
}

export interface ModelFlashscorePlayerInjury {
  "from"?: string;
  "type"?: string;
  "until"?: string;
}

export interface ModelFlashscorePlayerResponse {
  "age"?: number;
  "career"?: Array<ModelFlashscoreCareerTab>;
  "contract_expires"?: string;
  "details"?: Array<ModelFlashscorePlayerDetail>;
  "market_value"?: string;
  "page_url"?: string;
  "player"?: ModelFlashscorePlayerProfile;
  "position"?: string;
  "source_url"?: string;
}

export interface ModelFlashscorePlayerDetail {
  "label"?: string;
  "value"?: string;
}

export interface ModelFlashscoreCareerTab {
  "columns"?: Array<ModelFlashscoreSquadColumn>;
  "key"?: string;
  "name"?: string;
  "rows"?: Array<ModelFlashscoreCareerRow>;
  "total"?: Record<string, unknown>;
}

export interface ModelFlashscoreCareerRow {
  "competition"?: ModelFlashscoreCareerCompetition;
  "parts"?: Array<ModelFlashscoreCareerPart>;
  "season"?: string;
  "stats"?: Record<string, unknown>;
  "team"?: ModelFlashscoreCareerTeam;
}

export interface ModelFlashscoreCareerTeam {
  "id"?: string;
  "name"?: string;
  "path"?: string;
  "slug"?: string;
}

export interface ModelFlashscoreCareerPart {
  "stage"?: string;
  "stats"?: Record<string, unknown>;
}

export interface ModelFlashscoreCareerCompetition {
  "name"?: string;
  "path"?: string;
}

export interface ModelFlashscoreOddsGeosResponseDoc {
  "code"?: number;
  "data"?: ModelFlashscoreOddsGeosDataDoc;
  "msg"?: string;
}

export interface ModelFlashscoreOddsGeosDataDoc {
  "betting_scopes"?: Array<string>;
  "betting_types"?: Array<string>;
  "default_geo"?: string;
  "geos"?: Array<ModelFlashscoreOddsGeoDoc>;
  "handicap_types"?: Array<string>;
  "subdivision_notes"?: string;
  "subdivisions"?: Array<ModelFlashscoreOddsSubdivisionDoc>;
  "verified_on"?: string;
}

export interface ModelFlashscoreOddsSubdivisionDoc {
  "code"?: string;
  "geo"?: string;
  "name"?: string;
}

export interface ModelFlashscoreOddsGeoDoc {
  "code"?: string;
  "has_bookmakers"?: boolean;
  "name"?: string;
}

export interface ModelFlashscoreNewsMostReadResponse {
  "article_count"?: number;
  "articles"?: Array<ModelFlashscoreMostReadArticle>;
  "source_url"?: string;
}

export interface ModelFlashscoreMostReadArticle {
  "edited_at"?: number;
  "id"?: string;
  "image_alt"?: string;
  "image_credit"?: string;
  "image_url"?: string;
  "path"?: string;
  "published_at"?: number;
  "published_at_iso"?: string;
  "slug"?: string;
  "title"?: string;
  "type"?: string;
}

export interface ModelFlashscoreNewsCategoriesResponseDoc {
  "code"?: number;
  "data"?: ModelFlashscoreNewsCategoriesDataDoc;
  "msg"?: string;
}

export interface ModelFlashscoreNewsCategoriesDataDoc {
  "categories"?: Array<ModelFlashscoreNewsCategoryDoc>;
  "source_url"?: string;
}

export interface ModelFlashscoreNewsCategoryDoc {
  "entity_id"?: string;
  "entity_type"?: "SPORT" | "TOURNAMENT_TEMPLATE" | "TAG";
  "key"?: string;
  "name"?: string;
  "path"?: string;
}

export interface ModelFlashscoreNewsArticleBodyResponse {
  "article"?: ModelFlashscoreNewsArticleBody;
  "source_url"?: string;
}

export interface ModelFlashscoreNewsArticleBody {
  "author"?: string;
  "block_count"?: number;
  "blocks"?: Array<ModelFlashscoreNewsBodyBlock>;
  "credit"?: string;
  "edited_at"?: number;
  "edited_at_iso"?: string;
  "id"?: string;
  "image"?: ModelFlashscoreNewsCoverImage;
  "perex"?: string;
  "published_at"?: number;
  "published_at_iso"?: string;
  "slug"?: string;
  "tags"?: Array<ModelFlashscoreNewsArticleTag>;
  "text"?: string;
  "title"?: string;
  "type"?: string;
  "url"?: string;
}

export interface ModelFlashscoreNewsArticleTag {
  "entity_id"?: string;
  "entity_type"?: "SPORT" | "PARTICIPANT" | "TOURNAMENT_TEMPLATE" | "TAG";
  "label"?: string;
  "slug"?: string;
}

export interface ModelFlashscoreNewsCoverImage {
  "alt_text"?: string;
  "credit"?: string;
  "url"?: string;
}

export interface ModelFlashscoreNewsBodyBlock {
  "alt"?: string;
  "credit"?: string;
  "height"?: number;
  "id"?: string;
  "level"?: number;
  "links"?: Array<ModelFlashscoreNewsBodyLink>;
  "provider"?: string;
  "text"?: string;
  "type"?: "paragraph" | "heading" | "embed" | "image" | "infobox";
  "url"?: string;
  "width"?: number;
}

export interface ModelFlashscoreNewsBodyLink {
  "id"?: string;
  "kind"?: "link" | "participant" | "player" | "event" | "tournament" | "article";
  "sport_id"?: number;
  "text"?: string;
  "url"?: string;
}

export interface ModelFlashscoreNewsArticleResponseDoc {
  "code"?: number;
  "data"?: ModelFlashscoreNewsArticleDataDoc;
  "msg"?: string;
}

export interface ModelFlashscoreNewsArticleDataDoc {
  "article"?: ModelFlashscoreNewsArticleDoc;
  "source_url"?: string;
}

export interface ModelFlashscoreNewsArticleDoc {
  "edited_at"?: number;
  "id"?: string;
  "images"?: Array<ModelFlashscoreNewsImageDoc>;
  "published_at"?: number;
  "slug"?: string;
  "title"?: string;
  "type"?: string;
}

export interface ModelFlashscoreNewsImageDoc {
  "alt_text"?: string;
  "credit"?: string;
  "url"?: string;
  "variant_type_id"?: number;
}

export interface ModelFlashscoreNewsListResponseDoc {
  "code"?: number;
  "data"?: ModelFlashscoreNewsListDataDoc;
  "msg"?: string;
}

export interface ModelFlashscoreNewsListDataDoc {
  "articles"?: Array<ModelFlashscoreNewsPreviewDoc>;
  "category"?: ModelFlashscoreNewsCategoryDoc;
  "has_more"?: boolean;
  "page"?: number;
  "source_url"?: string;
}

export interface ModelFlashscoreNewsPreviewDoc {
  "date"?: string;
  "id"?: string;
  "image_alt"?: string;
  "image_url"?: string;
  "path"?: string;
  "title"?: string;
}

export interface ModelFlashscoreNavigationResponseDoc {
  "code"?: number;
  "data"?: ModelFlashscoreNavigationDataDoc;
  "msg"?: string;
}

export interface ModelFlashscoreNavigationDataDoc {
  "groups"?: Array<ModelFlashscoreNavigationGroupDoc>;
  "path"?: string;
  "source_url"?: string;
  "title"?: string;
}

export interface ModelFlashscoreNavigationGroupDoc {
  "items"?: Array<ModelFlashscoreNavigationItemDoc>;
  "name"?: string;
}

export interface ModelFlashscoreNavigationItemDoc {
  "id"?: number;
  "name"?: string;
  "path"?: string;
  "sport_id"?: number;
}

export interface ModelFlashscoreMatchTvresponseDoc {
  "code"?: number;
  "data"?: ModelFlashscoreMatchTvdataDoc;
  "msg"?: string;
}

export interface ModelFlashscoreMatchTvdataDoc {
  "broadcasters"?: Array<ModelFlashscoreBroadcasterDoc>;
  "geo"?: string;
  "match_id"?: string;
  "source_url"?: string;
}

export interface ModelFlashscoreBroadcasterDoc {
  "affiliate"?: boolean;
  "id"?: number;
  "name"?: string;
  "url"?: string;
}

export interface ModelFlashscoreMatchReportResponseDoc {
  "code"?: number;
  "data"?: ModelFlashscoreMatchReportDataDoc;
  "msg"?: string;
}

export interface ModelFlashscoreMatchReportDataDoc {
  "match_id"?: string;
  "report"?: ModelFlashscoreMatchReportDoc;
  "source_url"?: string;
}

export interface ModelFlashscoreMatchReportDoc {
  "author"?: string;
  "content"?: Array<ModelFlashscoreReportBlockDoc>;
  "edited_at"?: string;
  "id"?: string;
  "images"?: Array<ModelFlashscoreReportImageDoc>;
  "published_at"?: string;
  "text"?: string;
  "title"?: string;
}

export interface ModelFlashscoreReportImageDoc {
  "alt"?: string;
  "credit"?: string;
  "thumbnail_url"?: string;
  "url"?: string;
}

export interface ModelFlashscoreReportBlockDoc {
  "alt"?: string;
  "bold"?: boolean;
  "credit"?: string;
  "height"?: number;
  "links"?: Array<ModelFlashscoreReportLinkDoc>;
  "text"?: string;
  "type"?: "paragraph" | "image";
  "url"?: string;
  "width"?: number;
}

export interface ModelFlashscoreReportLinkDoc {
  "id"?: string;
  "text"?: string;
  "type"?: "team" | "player" | "competition" | "page";
  "url"?: string;
}

export interface ModelFlashscoreMatchPredictedLineupsResponseDoc {
  "code"?: number;
  "data"?: ModelFlashscoreMatchPredictedLineupsDataDoc;
  "msg"?: string;
}

export interface ModelFlashscoreMatchPredictedLineupsDataDoc {
  "match_id"?: string;
  "source_url"?: string;
  "teams"?: Array<ModelFlashscorePredictedLineupTeamDoc>;
}

export interface ModelFlashscorePredictedLineupTeamDoc {
  "aggregated_stats"?: ModelFlashscoreLineupAggregatedStatsDoc;
  "coaches"?: Array<ModelFlashscoreLineupPlayerDoc>;
  "formation"?: ModelFlashscorePredictedFormationDoc;
  "groups"?: Array<ModelFlashscoreLineupGroupDoc>;
  "name"?: string;
  "participant_id"?: string;
  "players"?: Array<ModelFlashscoreLineupPlayerDoc>;
  "side"?: "home" | "away";
}

export interface ModelFlashscoreLineupPlayerDoc {
  "age"?: number;
  "average_rating"?: number;
  "country"?: string;
  "height_cm"?: number;
  "id"?: string;
  "list_name"?: string;
  "market_value"?: number;
  "name"?: string;
  "number"?: string;
  "roles"?: Array<ModelFlashscoreLineupRoleDoc>;
  "slug"?: string;
}

export interface ModelFlashscoreLineupRoleDoc {
  "suffix"?: string;
  "title"?: string;
}

export interface ModelFlashscoreLineupGroupDoc {
  "name"?: string;
  "player_ids"?: Array<string>;
  "type"?: string;
}

export interface ModelFlashscorePredictedFormationDoc {
  "lines"?: Array<ModelFlashscoreFormationLineDoc>;
  "name"?: string;
}

export interface ModelFlashscoreFormationLineDoc {
  "number"?: number;
  "rows"?: Array<ModelFlashscoreFormationRowDoc>;
}

export interface ModelFlashscoreFormationRowDoc {
  "player_ids"?: Array<string>;
  "sort_key"?: number;
}

export interface ModelFlashscoreLineupAggregatedStatsDoc {
  "average_age"?: number;
  "average_height_cm"?: number;
  "average_rating"?: number;
  "sum_market_value"?: number;
}

export interface ModelFlashscoreMatchPointByPointResponseDoc {
  "code"?: number;
  "data"?: ModelFlashscoreMatchPointByPointDataDoc;
  "msg"?: string;
}

export interface ModelFlashscoreMatchPointByPointDataDoc {
  "current_game"?: ModelFlashscorePointByPointCurrentGameDoc;
  "match_id"?: string;
  "periods"?: Array<ModelFlashscorePointByPointPeriodDoc>;
  "source_url"?: string;
}

export interface ModelFlashscorePointByPointPeriodDoc {
  "sections"?: Array<ModelFlashscorePointByPointSectionDoc>;
  "title"?: string;
}

export interface ModelFlashscorePointByPointSectionDoc {
  "entries"?: Array<ModelFlashscorePointByPointEntryDoc>;
  "title"?: string;
}

export interface ModelFlashscorePointByPointEntryDoc {
  "away_score"?: number;
  "away_tiebreak_score"?: number;
  "home_score"?: number;
  "home_tiebreak_score"?: number;
  "lead"?: ModelFlashscorePointByPointLeadDoc;
  "markers"?: Array<ModelFlashscorePointMarkerDoc>;
  "number"?: number;
  "points"?: Array<ModelFlashscorePointScoreDoc>;
  "server"?: "home" | "away";
  "server_lost"?: boolean;
  "winner"?: "home" | "away";
}

export interface ModelFlashscorePointScoreDoc {
  "away"?: string;
  "home"?: string;
  "markers"?: Array<ModelFlashscorePointMarkerDoc>;
}

export interface ModelFlashscorePointMarkerDoc {
  "side"?: "home" | "away";
  "type"?: "break_point" | "set_point" | "match_point";
}

export interface ModelFlashscorePointByPointLeadDoc {
  "margin"?: number;
  "narrowed"?: boolean;
  "side"?: "home" | "away";
}

export interface ModelFlashscorePointByPointCurrentGameDoc {
  "points"?: Array<ModelFlashscorePointScoreDoc>;
  "server"?: "home" | "away";
  "title"?: string;
}

export interface ModelFlashscoreMatchPlayerStatsResponseDoc {
  "code"?: number;
  "data"?: ModelFlashscoreMatchPlayerStatsDataDoc;
  "msg"?: string;
}

export interface ModelFlashscoreMatchPlayerStatsDataDoc {
  "groups"?: Array<ModelFlashscorePlayerStatGroupDoc>;
  "match_id"?: string;
  "players"?: Array<ModelFlashscorePlayerMatchStatsDoc>;
  "source_url"?: string;
  "stat_types"?: Array<ModelFlashscorePlayerStatTypeDoc>;
  "teams"?: Array<ModelFlashscorePlayerStatTeamDoc>;
}

export interface ModelFlashscorePlayerStatTeamDoc {
  "id"?: string;
  "name"?: string;
  "side"?: "home" | "away";
}

export interface ModelFlashscorePlayerStatTypeDoc {
  "combined"?: ModelFlashscorePlayerStatCombinedDoc;
  "format"?: "count" | "percentage" | "count_two_decimal_places";
  "groups"?: Array<"top_stats" | "shots" | "attack" | "passes" | "defense" | "goalkeeping" | "general">;
  "key"?: string;
  "label"?: string;
  "sentiment"?: "positive" | "negative";
}

export interface ModelFlashscorePlayerStatCombinedDoc {
  "stats"?: Array<string>;
  "template"?: string;
}

export interface ModelFlashscorePlayerMatchStatsDoc {
  "highlights"?: Array<string>;
  "id"?: string;
  "name"?: string;
  "position"?: string;
  "rating"?: number;
  "short_name"?: string;
  "side"?: "home" | "away";
  "slug"?: string;
  "starter"?: boolean;
  "stats"?: Record<string, ModelFlashscorePlayerStatValueDoc>;
  "team_id"?: string;
  "top_rated"?: boolean;
}

export interface ModelFlashscorePlayerStatValueDoc {
  "rank"?: number;
  "raw"?: number;
  "value"?: string;
}

export interface ModelFlashscorePlayerStatGroupDoc {
  "goalkeeper_only"?: boolean;
  "key"?: "top_stats" | "shots" | "attack" | "passes" | "defense" | "goalkeeping" | "general";
  "label"?: string;
  "stats"?: Array<string>;
}

export interface ModelFlashscoreMatchOddsResponseDoc {
  "code"?: number;
  "data"?: ModelFlashscoreMatchOddsDataDoc;
  "msg"?: string;
}

export interface ModelFlashscoreMatchOddsDataDoc {
  "bookmakers"?: Array<ModelFlashscoreOddsBookmakerDoc>;
  "geo"?: string;
  "markets"?: Array<ModelFlashscoreOddsMarketDoc>;
  "match_id"?: string;
  "participants"?: Array<ModelFlashscoreOddsParticipantDoc>;
  "source_url"?: string;
  "subdivision"?: string;
}

export interface ModelFlashscoreOddsParticipantDoc {
  "id"?: string;
  "side"?: "home" | "away";
}

export interface ModelFlashscoreOddsMarketDoc {
  "betting_type"?: "HOME_DRAW_AWAY" | "HOME_AWAY" | "DRAW_NO_BET" | "DOUBLE_CHANCE" | "ASIAN_HANDICAP" | "EUROPEAN_HANDICAP" | "OVER_UNDER" | "BOTH_TEAMS_TO_SCORE" | "CORRECT_SCORE" | "HALF_FULL_TIME" | "ODD_OR_EVEN" | "TO_QUALIFY" | "NEXT_GOAL" | "TOP_POSITION_MERGED" | "TO_WIN_AND_TOP_POSITION" | "WIN_EACH_WAY";
  "offers"?: Array<ModelFlashscoreOddsOfferDoc>;
  "scope"?: "FULL_TIME" | "FULL_TIME_OVER_TIME" | "FIRST_HALF" | "SECOND_HALF" | "FIRST_PERIOD" | "FIRST_QUARTER" | "FIRST_SET" | "SECOND_SET";
}

export interface ModelFlashscoreOddsOfferDoc {
  "bookmaker_id"?: number;
  "outcomes"?: Array<ModelFlashscoreOddsOutcomeDoc>;
}

export interface ModelFlashscoreOddsOutcomeDoc {
  "active"?: boolean;
  "half_full_time"?: string;
  "handicap"?: number;
  "handicap_type"?: "UNKNOWN" | "GOALS" | "GAMES" | "SETS" | "POINTS" | "FRAMES" | "LEGS" | "RUNS";
  "odds"?: number;
  "opening_odds"?: number;
  "participant_id"?: string;
  "score"?: string;
  "selection"?: string;
  "side"?: "home" | "away";
}

export interface ModelFlashscoreOddsBookmakerDoc {
  "id"?: number;
  "name"?: string;
}

export interface ModelFlashscoreMatchNewsResponseDoc {
  "code"?: number;
  "data"?: ModelFlashscoreMatchNewsDataDoc;
  "msg"?: string;
}

export interface ModelFlashscoreMatchNewsDataDoc {
  "layout_id"?: number;
  "match_id"?: string;
  "name"?: string;
  "sections"?: Array<ModelFlashscoreMatchNewsSectionDoc>;
  "source_url"?: string;
}

export interface ModelFlashscoreMatchNewsSectionDoc {
  "articles"?: Array<ModelFlashscoreMatchNewsArticleRefDoc>;
  "id"?: number;
  "name"?: string;
}

export interface ModelFlashscoreMatchNewsArticleRefDoc {
  "article"?: ModelFlashscoreMatchNewsArticleSortKeyDoc;
  "id"?: string;
}

export interface ModelFlashscoreMatchNewsArticleSortKeyDoc {
  "sort_key"?: number;
}

export interface ModelFlashscoreMatchMomentumResponseDoc {
  "code"?: number;
  "data"?: ModelFlashscoreMatchMomentumDataDoc;
  "msg"?: string;
}

export interface ModelFlashscoreMatchMomentumDataDoc {
  "event_types"?: Array<ModelFlashscoreMomentumEventTypeDoc>;
  "events"?: Array<ModelFlashscoreMomentumEventDoc>;
  "match_id"?: string;
  "momentum"?: Array<ModelFlashscoreMomentumFrameDoc>;
  "source_url"?: string;
  "teams"?: Array<ModelFlashscoreMomentumTeamDoc>;
}

export interface ModelFlashscoreMomentumTeamDoc {
  "code"?: string;
  "id"?: string;
  "side"?: "home" | "away";
}

export interface ModelFlashscoreMomentumFrameDoc {
  "added_time"?: number;
  "elapsed_minute"?: number;
  "elapsed_second"?: number;
  "minute"?: string;
  "period"?: "first_half" | "second_half" | "extra_time" | "first_extra_time" | "second_extra_time" | "unknown";
  "stage_id"?: number;
  "value"?: number;
}

export interface ModelFlashscoreMomentumEventDoc {
  "id"?: string;
  "label"?: string;
  "minute"?: string;
  "period"?: "first_half" | "second_half" | "extra_time" | "first_extra_time" | "second_extra_time" | "unknown";
  "player_id"?: string;
  "player_name"?: string;
  "side"?: "home" | "away";
  "stage_id"?: number;
  "team_id"?: string;
  "type"?: "yellow_red_card" | "red_card" | "goal" | "own_goal" | "penalty_goal";
}

export interface ModelFlashscoreMomentumEventTypeDoc {
  "label"?: string;
  "type"?: "yellow_red_card" | "red_card" | "goal" | "own_goal" | "penalty_goal";
}

export interface ModelFlashscoreMatchMissingPlayersResponseDoc {
  "code"?: number;
  "data"?: ModelFlashscoreMatchMissingPlayersDataDoc;
  "msg"?: string;
}

export interface ModelFlashscoreMatchMissingPlayersDataDoc {
  "match_id"?: string;
  "source_url"?: string;
  "teams"?: Array<ModelFlashscoreMissingPlayersTeamDoc>;
}

export interface ModelFlashscoreMissingPlayersTeamDoc {
  "doubtful"?: Array<ModelFlashscoreMissingPlayerDoc>;
  "missing"?: Array<ModelFlashscoreMissingPlayerDoc>;
  "participant_id"?: string;
  "side"?: "home" | "away";
}

export interface ModelFlashscoreMissingPlayerDoc {
  "country"?: string;
  "list_name"?: string;
  "name"?: string;
  "player_id"?: string;
  "reason"?: string;
  "slug"?: string;
}

export interface ModelFlashscoreMatchDartsResponseDoc {
  "code"?: number;
  "data"?: ModelFlashscoreMatchDartsDataDoc;
  "msg"?: string;
}

export interface ModelFlashscoreMatchDartsDataDoc {
  "legs"?: Array<ModelFlashscoreDartsLegDoc>;
  "match_id"?: string;
  "source_url"?: string;
  "statistics"?: Array<ModelFlashscoreDartsStatisticDoc>;
  "statistics_url"?: string;
}

export interface ModelFlashscoreDartsStatisticDoc {
  "away"?: string;
  "home"?: string;
  "id"?: string;
  "key"?: "average_3_darts" | "180_thrown" | "140_plus_thrown" | "100_plus_thrown" | "checkouts" | "checkouts_100_plus" | "highest_checkout";
  "name"?: string;
}

export interface ModelFlashscoreDartsLegDoc {
  "away_legs"?: number;
  "checkout"?: number;
  "home_legs"?: number;
  "number"?: number;
  "start_score"?: number;
  "starter"?: "home" | "away";
  "visits"?: Array<ModelFlashscoreDartsVisitDoc>;
  "winner"?: "home" | "away";
}

export interface ModelFlashscoreDartsVisitDoc {
  "highlight"?: "180" | "140_plus";
  "number"?: number;
  "remaining"?: number;
  "scored"?: number;
  "side"?: "home" | "away";
}

export interface ModelFlashscoreMatchBoxScoreResponseDoc {
  "code"?: number;
  "data"?: ModelFlashscoreMatchBoxScoreDataDoc;
  "msg"?: string;
}

export interface ModelFlashscoreMatchBoxScoreDataDoc {
  "match_id"?: string;
  "source_url"?: string;
  "teams"?: Array<ModelFlashscoreMatchBoxScoreTeamDoc>;
}

export interface ModelFlashscoreMatchBoxScoreTeamDoc {
  "name"?: string;
  "side"?: "home" | "away";
  "tables"?: Array<ModelFlashscoreMatchBoxScoreTableDoc>;
}

export interface ModelFlashscoreMatchBoxScoreTableDoc {
  "columns"?: Array<ModelFlashscoreMatchBoxScoreColumnDoc>;
  "player_label"?: string;
  "players"?: Array<ModelFlashscoreMatchBoxScorePlayerDoc>;
  "type"?: "player" | "goalkeeper" | "pitcher";
}

export interface ModelFlashscoreMatchBoxScorePlayerDoc {
  "country"?: string;
  "name"?: string;
  "player_id"?: string;
  "slug"?: string;
  "stats"?: Record<string, string>;
  "status"?: string;
}

export interface ModelFlashscoreMatchBoxScoreColumnDoc {
  "format"?: "num" | "time" | "fg";
  "key"?: string;
  "label"?: string;
}

export interface ModelFlashscoreEntityNewsResponse {
  "article_count"?: number;
  "entity"?: ModelFlashscoreEntityNewsTag;
  "id"?: string;
  "sections"?: Array<ModelFlashscoreEntityNewsSection>;
  "source_url"?: string;
  "title"?: string;
  "type"?: "team" | "player" | "tournament" | "sport";
}

export interface ModelFlashscoreEntityNewsSection {
  "article_count"?: number;
  "article_ids"?: Array<string>;
  "section_type"?: "MOST_RECENT" | "TOPPED";
  "title"?: string;
}

export interface ModelFlashscoreEntityNewsTag {
  "entity_id"?: string;
  "entity_type"?: "PARTICIPANT" | "TOURNAMENT_TEMPLATE" | "SPORT";
  "label"?: string;
  "slug"?: string;
}

export interface ModelFlashscoreCompetitionsResponseDoc {
  "code"?: number;
  "data"?: ModelFlashscoreCompetitionsDataDoc;
  "msg"?: string;
}

export interface ModelFlashscoreCompetitionsDataDoc {
  "competitions"?: Array<ModelFlashscoreCompetitionDoc>;
  "day_offset"?: number;
  "source_url"?: string;
  "sport"?: string;
}

export interface ModelFlashscoreCompetitionDoc {
  "event_count"?: number;
  "id"?: string;
  "name"?: string;
  "path"?: string;
  "region"?: string;
}

export interface ModelFlashscoreCalendarCategoriesResponseDoc {
  "code"?: number;
  "data"?: ModelFlashscoreCalendarCategoriesDataDoc;
  "msg"?: string;
}

export interface ModelFlashscoreCalendarCategoriesDataDoc {
  "categories"?: Array<ModelFlashscoreCalendarCategoryDoc>;
  "source_url"?: string;
}

export interface ModelFlashscoreCalendarCategoryDoc {
  "key"?: string;
  "name"?: string;
  "path"?: string;
  "sport"?: string;
}

export interface ModelFlashscoreCalendarResponseDoc {
  "code"?: number;
  "data"?: ModelFlashscoreCalendarDataDoc;
  "msg"?: string;
}

export interface ModelFlashscoreCalendarDataDoc {
  "category"?: ModelFlashscoreCalendarCategoryDoc;
  "events"?: Array<ModelFlashscoreCalendarEventDoc>;
  "source_url"?: string;
  "year"?: number;
}

export interface ModelFlashscoreCalendarEventDoc {
  "country"?: string;
  "date"?: string;
  "end_time"?: string;
  "month"?: string;
  "name"?: string;
  "path"?: string;
  "start_time"?: string;
  "winner"?: string;
  "winner_path"?: string;
}

export type FlashscoreCalendarResponse = CrawloraResponse<ModelFlashscoreCalendarResponseDoc>;
export interface FlashscoreCalendarParams {
  "category": "tennis-atp" | "tennis-wta" | "golf-pga" | "golf-dp-world" | "badminton-bwf" | "motorsport-f1";
}

export type FlashscoreCalendarCategoriesResponse = CrawloraResponse<ModelFlashscoreCalendarCategoriesResponseDoc>;
export interface FlashscoreCalendarCategoriesParams {
}

export type FlashscoreCompetitionsResponse = CrawloraResponse<ModelFlashscoreCompetitionsResponseDoc>;
export interface FlashscoreCompetitionsParams {
  "sport": "football" | "tennis" | "basketball" | "hockey" | "golf" | "formula-1" | "baseball" | "snooker" | "american-football" | "aussie-rules" | "badminton" | "bandy" | "beach-soccer" | "beach-volleyball" | "boxing" | "cricket" | "cycling" | "darts" | "esports" | "field-hockey" | "floorball" | "futsal" | "handball" | "horse-racing" | "kabaddi" | "mma" | "motorsport" | "netball" | "pesapallo" | "rugby-league" | "rugby-union" | "table-tennis" | "volleyball" | "water-polo" | "winter-sports" | "moto-racing" | "ski-jumping" | "alpine-skiing" | "cross-country-skiing" | "biathlon";
  "day_offset"?: number;
}

export type FlashscoreEntityNewsResponse = CrawloraResponse<ModelAppResponse & { "data"?: ModelFlashscoreEntityNewsResponse }>;
export interface FlashscoreEntityNewsParams {
  "type": "team" | "player" | "tournament" | "sport";
  "id": string;
}

export type FlashscoreMatchBoxScoreResponse = CrawloraResponse<ModelFlashscoreMatchBoxScoreResponseDoc>;
export interface FlashscoreMatchBoxScoreParams {
  "id": string;
}

export type FlashscoreMatchDartsResponse = CrawloraResponse<ModelFlashscoreMatchDartsResponseDoc>;
export interface FlashscoreMatchDartsParams {
  "id": string;
}

export type FlashscoreMatchH2hResponse = CrawloraResponse<ModelFlashscoreResponseDoc>;
export interface FlashscoreMatchH2hParams {
  "id": string;
}

export type FlashscoreMatchHighlightsResponse = CrawloraResponse<ModelFlashscoreResponseDoc>;
export interface FlashscoreMatchHighlightsParams {
  "id": string;
}

export type FlashscoreMatchInfoResponse = CrawloraResponse<ModelFlashscoreResponseDoc>;
export interface FlashscoreMatchInfoParams {
  "id": string;
}

export type FlashscoreMatchLineupsResponse = CrawloraResponse<ModelFlashscoreResponseDoc>;
export interface FlashscoreMatchLineupsParams {
  "id": string;
}

export type FlashscoreMatchMissingPlayersResponse = CrawloraResponse<ModelFlashscoreMatchMissingPlayersResponseDoc>;
export interface FlashscoreMatchMissingPlayersParams {
  "id": string;
}

export type FlashscoreMatchMomentumResponse = CrawloraResponse<ModelFlashscoreMatchMomentumResponseDoc>;
export interface FlashscoreMatchMomentumParams {
  "id": string;
}

export type FlashscoreMatchNewsResponse = CrawloraResponse<ModelFlashscoreMatchNewsResponseDoc>;
export interface FlashscoreMatchNewsParams {
  "id": string;
}

export type FlashscoreMatchOddsResponse = CrawloraResponse<ModelFlashscoreMatchOddsResponseDoc>;
export interface FlashscoreMatchOddsParams {
  "id": string;
  "geo"?: "AE" | "AL" | "AM" | "AO" | "AR" | "AT" | "AU" | "AZ" | "BA" | "BD" | "BE" | "BG" | "BO" | "BR" | "BY" | "CA" | "CH" | "CI" | "CL" | "CM" | "CN" | "CO" | "CR" | "CY" | "CZ" | "DE" | "DK" | "DO" | "DZ" | "EC" | "EE" | "EG" | "ES" | "ET" | "FI" | "FR" | "GB" | "GE" | "GH" | "GR" | "GT" | "HK" | "HN" | "HR" | "HU" | "ID" | "IE" | "IL" | "IN" | "IQ" | "IR" | "IS" | "IT" | "JO" | "JP" | "KE" | "KG" | "KH" | "KR" | "KW" | "KZ" | "LA" | "LB" | "LK" | "LT" | "LU" | "LV" | "LY" | "MA" | "MD" | "ME" | "MK" | "MM" | "MN" | "MT" | "MX" | "MY" | "NG" | "NI" | "NL" | "NO" | "NP" | "NZ" | "PA" | "PE" | "PH" | "PK" | "PL" | "PT" | "PY" | "QA" | "RO" | "RS" | "RU" | "SA" | "SD" | "SE" | "SG" | "SI" | "SK" | "SN" | "SV" | "TH" | "TN" | "TR" | "TW" | "TZ" | "UA" | "UG" | "US" | "UY" | "UZ" | "VE" | "VN" | "XK" | "ZA" | "ZM" | "ZW";
  "subdivision"?: "AB" | "AK" | "AL" | "AR" | "AZ" | "BC" | "CA" | "CO" | "CT" | "DC" | "DE" | "FL" | "GA" | "HI" | "IA" | "ID" | "IL" | "IN" | "KS" | "KY" | "LA" | "MA" | "MB" | "MD" | "ME" | "MI" | "MN" | "MO" | "MS" | "MT" | "NB" | "NC" | "ND" | "NE" | "NH" | "NJ" | "NL" | "NM" | "NS" | "NT" | "NU" | "NV" | "NY" | "OH" | "OK" | "ON" | "OR" | "PA" | "PE" | "QC" | "RI" | "SC" | "SD" | "SK" | "TN" | "TX" | "UT" | "VA" | "VT" | "WA" | "WI" | "WV" | "WY" | "YT";
  "betting_type"?: "HOME_DRAW_AWAY" | "HOME_AWAY" | "DRAW_NO_BET" | "DOUBLE_CHANCE" | "ASIAN_HANDICAP" | "EUROPEAN_HANDICAP" | "OVER_UNDER" | "BOTH_TEAMS_TO_SCORE" | "CORRECT_SCORE" | "HALF_FULL_TIME" | "ODD_OR_EVEN" | "TO_QUALIFY" | "NEXT_GOAL" | "TOP_POSITION_MERGED" | "TO_WIN_AND_TOP_POSITION" | "WIN_EACH_WAY";
  "scope"?: "FULL_TIME" | "FULL_TIME_OVER_TIME" | "FIRST_HALF" | "SECOND_HALF" | "FIRST_PERIOD" | "FIRST_QUARTER" | "FIRST_SET" | "SECOND_SET";
}

export type FlashscoreMatchPlayerStatsResponse = CrawloraResponse<ModelFlashscoreMatchPlayerStatsResponseDoc>;
export interface FlashscoreMatchPlayerStatsParams {
  "id": string;
  "player_id"?: string;
  "group"?: "top_stats" | "shots" | "attack" | "passes" | "defense" | "goalkeeping" | "general";
}

export type FlashscoreMatchPointByPointResponse = CrawloraResponse<ModelFlashscoreMatchPointByPointResponseDoc>;
export interface FlashscoreMatchPointByPointParams {
  "id": string;
}

export type FlashscoreMatchPredictedLineupsResponse = CrawloraResponse<ModelFlashscoreMatchPredictedLineupsResponseDoc>;
export interface FlashscoreMatchPredictedLineupsParams {
  "id": string;
}

export type FlashscoreMatchReportResponse = CrawloraResponse<ModelFlashscoreMatchReportResponseDoc>;
export interface FlashscoreMatchReportParams {
  "id": string;
}

export type FlashscoreMatchStandingsResponse = CrawloraResponse<ModelFlashscoreResponseDoc>;
export interface FlashscoreMatchStandingsParams {
  "id": string;
  "view"?: "overall" | "home" | "away" | "form_overall" | "overunder_overall" | "form_home" | "form_away" | "top_scorers" | "htft_overall" | "htft_home" | "htft_away" | "live_overall" | "overunder_home" | "overunder_away";
}

export type FlashscoreMatchStatsResponse = CrawloraResponse<ModelFlashscoreResponseDoc>;
export interface FlashscoreMatchStatsParams {
  "id": string;
}

export type FlashscoreMatchTvResponse = CrawloraResponse<ModelFlashscoreMatchTvresponseDoc>;
export interface FlashscoreMatchTvParams {
  "id": string;
  "geo"?: "AE" | "AL" | "AM" | "AO" | "AR" | "AT" | "AU" | "AZ" | "BA" | "BD" | "BE" | "BG" | "BO" | "BR" | "BY" | "CA" | "CH" | "CI" | "CL" | "CM" | "CN" | "CO" | "CR" | "CY" | "CZ" | "DE" | "DK" | "DO" | "DZ" | "EC" | "EE" | "EG" | "ES" | "ET" | "FI" | "FR" | "GB" | "GE" | "GH" | "GR" | "GT" | "HK" | "HN" | "HR" | "HU" | "ID" | "IE" | "IL" | "IN" | "IQ" | "IR" | "IS" | "IT" | "JO" | "JP" | "KE" | "KG" | "KH" | "KR" | "KW" | "KZ" | "LA" | "LB" | "LK" | "LT" | "LU" | "LV" | "LY" | "MA" | "MD" | "ME" | "MK" | "MM" | "MN" | "MT" | "MX" | "MY" | "NG" | "NI" | "NL" | "NO" | "NP" | "NZ" | "PA" | "PE" | "PH" | "PK" | "PL" | "PT" | "PY" | "QA" | "RO" | "RS" | "RU" | "SA" | "SD" | "SE" | "SG" | "SI" | "SK" | "SN" | "SV" | "TH" | "TN" | "TR" | "TW" | "TZ" | "UA" | "UG" | "US" | "UY" | "UZ" | "VE" | "VN" | "XK" | "ZA" | "ZM" | "ZW";
}

export type FlashscoreNavigationResponse = CrawloraResponse<ModelFlashscoreNavigationResponseDoc>;
export interface FlashscoreNavigationParams {
  "path"?: string;
}

export type FlashscoreNewsResponse = CrawloraResponse<ModelFlashscoreNewsListResponseDoc>;
export interface FlashscoreNewsParams {
  "category"?: "all" | "football" | "uefa-nations-league" | "tennis" | "features" | "premier-league" | "nfl" | "mlb" | "nba" | "nhl" | "formula-1" | "champions-league" | "europa-league" | "conference-league" | "darts" | "snooker" | "golf" | "road-cycling" | "laliga" | "bundesliga" | "serie-a" | "ligue-1" | "badminton" | "handball" | "hockey" | "basketball" | "cricket" | "rugby-union" | "athletics" | "baseball" | "fifa" | "rugby-league" | "motorsport" | "aussie-rules" | "flashscore-ratings" | "american-sports" | "african-football" | "combat-sports" | "winter-sports" | "transfer-news";
  "page"?: number;
}

export type FlashscoreNewsArticleResponse = CrawloraResponse<ModelFlashscoreNewsArticleResponseDoc>;
export interface FlashscoreNewsArticleParams {
  "id": string;
}

export type FlashscoreNewsArticleBodyResponse = CrawloraResponse<ModelAppResponse & { "data"?: ModelFlashscoreNewsArticleBodyResponse }>;
export interface FlashscoreNewsArticleBodyParams {
  "id": string;
}

export type FlashscoreNewsCategoriesResponse = CrawloraResponse<ModelFlashscoreNewsCategoriesResponseDoc>;
export interface FlashscoreNewsCategoriesParams {
}

export type FlashscoreNewsMostReadResponse = CrawloraResponse<ModelAppResponse & { "data"?: ModelFlashscoreNewsMostReadResponse }>;
export interface FlashscoreNewsMostReadParams {
}

export type FlashscoreOddsGeosResponse = CrawloraResponse<ModelFlashscoreOddsGeosResponseDoc>;
export interface FlashscoreOddsGeosParams {
}

export type FlashscorePlayerResponse = CrawloraResponse<ModelAppResponse & { "data"?: ModelFlashscorePlayerResponse }>;
export interface FlashscorePlayerParams {
  "id": string;
  "slug"?: string;
}

export type FlashscorePlayerFixturesResponse = CrawloraResponse<ModelAppResponse & { "data"?: ModelFlashscorePlayerEventsResponse }>;
export interface FlashscorePlayerFixturesParams {
  "id": string;
  "page"?: number;
}

export type FlashscorePlayerInjuriesResponse = CrawloraResponse<ModelAppResponse & { "data"?: ModelFlashscorePlayerInjuriesResponse }>;
export interface FlashscorePlayerInjuriesParams {
  "id": string;
  "slug"?: string;
}

export type FlashscorePlayerMatchLogResponse = CrawloraResponse<ModelAppResponse & { "data"?: ModelFlashscorePlayerMatchLogResponse }>;
export interface FlashscorePlayerMatchLogParams {
  "id": string;
  "page"?: number;
}

export type FlashscorePlayerNewsResponse = CrawloraResponse<ModelAppResponse & { "data"?: ModelFlashscorePlayerNewsResponse }>;
export interface FlashscorePlayerNewsParams {
  "id": string;
}

export type FlashscorePlayerResultsResponse = CrawloraResponse<ModelAppResponse & { "data"?: ModelFlashscorePlayerEventsResponse }>;
export interface FlashscorePlayerResultsParams {
  "id": string;
  "page"?: number;
}

export type FlashscorePlayerTransfersResponse = CrawloraResponse<ModelAppResponse & { "data"?: ModelFlashscorePlayerTransfersResponse }>;
export interface FlashscorePlayerTransfersParams {
  "id": string;
  "slug"?: string;
}

export type FlashscoreRankingCategoriesResponse = CrawloraResponse<ModelFlashscoreRankingCategoriesResponseDoc>;
export interface FlashscoreRankingCategoriesParams {
}

export type FlashscoreRankingsResponse = CrawloraResponse<ModelFlashscoreRankingResponseDoc>;
export interface FlashscoreRankingsParams {
  "category": "fifa" | "tennis-atp" | "tennis-wta" | "tennis-atp-race" | "tennis-wta-race" | "tennis-atp-doubles" | "tennis-wta-doubles" | "tennis-atp-doubles-race" | "tennis-wta-doubles-race" | "badminton-bwf-singles-men" | "badminton-bwf-singles-women" | "badminton-bwf-doubles-men" | "badminton-bwf-doubles-women" | "badminton-bwf-mixed-doubles" | "golf-owgr" | "golf-wwgr" | "golf-pga-fedexcup" | "golf-pga-money" | "golf-dp-world-tour" | "golf-lpga" | "golf-asian-tour" | "golf-japan-tour" | "golf-sunshine-tour" | "golf-korn-ferry" | "golf-champions-tour" | "darts-world-ranking" | "snooker-world-ranking" | "tennis-atp-live" | "tennis-wta-live" | "tennis-atp-race-live" | "tennis-wta-race-live" | "tennis-atp-doubles-live" | "tennis-wta-doubles-live" | "tennis-atp-doubles-race-live" | "tennis-wta-doubles-race-live";
}

export type FlashscoreScoresResponse = CrawloraResponse<ModelFlashscoreResponseDoc>;
export interface FlashscoreScoresParams {
  "sport": "football" | "tennis" | "basketball" | "hockey" | "golf" | "formula-1" | "baseball" | "snooker" | "american-football" | "aussie-rules" | "badminton" | "bandy" | "beach-soccer" | "beach-volleyball" | "boxing" | "cricket" | "cycling" | "darts" | "esports" | "field-hockey" | "floorball" | "futsal" | "handball" | "horse-racing" | "kabaddi" | "mma" | "motorsport" | "netball" | "pesapallo" | "rugby-league" | "rugby-union" | "table-tennis" | "volleyball" | "water-polo" | "winter-sports" | "moto-racing" | "ski-jumping" | "alpine-skiing" | "cross-country-skiing" | "biathlon";
  "day_offset"?: number;
}

export type FlashscoreSearchResponse = CrawloraResponse<ModelFlashscoreSearchResponseDoc>;
export interface FlashscoreSearchParams {
  "q": string;
}

export type FlashscoreSportsResponse = CrawloraResponse<ModelFlashscoreSportsResponseDoc>;
export interface FlashscoreSportsParams {
}

export type FlashscoreTeamResponse = CrawloraResponse<ModelAppResponse & { "data"?: ModelFlashscoreTeamResponse }>;
export interface FlashscoreTeamParams {
  "id": string;
}

export type FlashscoreTeamFixturesResponse = CrawloraResponse<ModelAppResponse & { "data"?: ModelFlashscoreTeamEventsResponse }>;
export interface FlashscoreTeamFixturesParams {
  "id": string;
  "page"?: number;
}

export type FlashscoreTeamNewsResponse = CrawloraResponse<ModelAppResponse & { "data"?: ModelFlashscoreTeamNewsResponse }>;
export interface FlashscoreTeamNewsParams {
  "id": string;
}

export type FlashscoreTeamOutrightOddsResponse = CrawloraResponse<ModelAppResponse & { "data"?: ModelFlashscoreTeamOutrightOddsResponse }>;
export interface FlashscoreTeamOutrightOddsParams {
  "id": string;
  "geo"?: "AE" | "AL" | "AM" | "AO" | "AR" | "AT" | "AU" | "AZ" | "BA" | "BD" | "BE" | "BG" | "BO" | "BR" | "BY" | "CA" | "CH" | "CI" | "CL" | "CM" | "CN" | "CO" | "CR" | "CY" | "CZ" | "DE" | "DK" | "DO" | "DZ" | "EC" | "EE" | "EG" | "ES" | "ET" | "FI" | "FR" | "GB" | "GE" | "GH" | "GR" | "GT" | "HK" | "HN" | "HR" | "HU" | "ID" | "IE" | "IL" | "IN" | "IQ" | "IR" | "IS" | "IT" | "JO" | "JP" | "KE" | "KG" | "KH" | "KR" | "KW" | "KZ" | "LA" | "LB" | "LK" | "LT" | "LU" | "LV" | "LY" | "MA" | "MD" | "ME" | "MK" | "MM" | "MN" | "MT" | "MX" | "MY" | "NG" | "NI" | "NL" | "NO" | "NP" | "NZ" | "PA" | "PE" | "PH" | "PK" | "PL" | "PT" | "PY" | "QA" | "RO" | "RS" | "RU" | "SA" | "SD" | "SE" | "SG" | "SI" | "SK" | "SN" | "SV" | "TH" | "TN" | "TR" | "TW" | "TZ" | "UA" | "UG" | "US" | "UY" | "UZ" | "VE" | "VN" | "XK" | "ZA" | "ZM" | "ZW";
  "subdivision"?: "AB" | "AK" | "AL" | "AR" | "AZ" | "BC" | "CA" | "CO" | "CT" | "DC" | "DE" | "FL" | "GA" | "HI" | "IA" | "ID" | "IL" | "IN" | "KS" | "KY" | "LA" | "MA" | "MB" | "MD" | "ME" | "MI" | "MN" | "MO" | "MS" | "MT" | "NB" | "NC" | "ND" | "NE" | "NH" | "NJ" | "NL" | "NM" | "NS" | "NT" | "NU" | "NV" | "NY" | "OH" | "OK" | "ON" | "OR" | "PA" | "PE" | "QC" | "RI" | "SC" | "SD" | "SK" | "TN" | "TX" | "UT" | "VA" | "VT" | "WA" | "WI" | "WV" | "WY" | "YT";
}

export type FlashscoreTeamResultsResponse = CrawloraResponse<ModelAppResponse & { "data"?: ModelFlashscoreTeamEventsResponse }>;
export interface FlashscoreTeamResultsParams {
  "id": string;
  "page"?: number;
}

export type FlashscoreTeamSquadResponse = CrawloraResponse<ModelAppResponse & { "data"?: ModelFlashscoreTeamSquadResponse }>;
export interface FlashscoreTeamSquadParams {
  "id": string;
  "slug"?: string;
  "scope"?: string;
}

export type FlashscoreTeamTransfersResponse = CrawloraResponse<ModelAppResponse & { "data"?: ModelFlashscoreTeamTransfersResponse }>;
export interface FlashscoreTeamTransfersParams {
  "id": string;
  "type"?: "all" | "arrivals" | "departures";
  "page"?: number;
}

export type FlashscoreTopSearchResponse = CrawloraResponse<ModelFlashscoreTopSearchResponseDoc>;
export interface FlashscoreTopSearchParams {
}

export type FlashscoreTournamentArchiveSeasonsResponse = CrawloraResponse<ModelAppResponse & { "data"?: ModelFlashscoreTournamentArchiveSeasonsResponse }>;
export interface FlashscoreTournamentArchiveSeasonsParams {
  "stage_id": string;
}

export type FlashscoreTournamentEventsResponse = CrawloraResponse<ModelFlashscoreTournamentEventsResponseDoc>;
export interface FlashscoreTournamentEventsParams {
  "path": string;
  "page"?: number;
}

export type FlashscoreTournamentOutrightOddsResponse = CrawloraResponse<ModelAppResponse & { "data"?: ModelFlashscoreTournamentOutrightOddsResponse }>;
export interface FlashscoreTournamentOutrightOddsParams {
  "tournament_id": string;
  "geo"?: "AE" | "AL" | "AM" | "AO" | "AR" | "AT" | "AU" | "AZ" | "BA" | "BD" | "BE" | "BG" | "BO" | "BR" | "BY" | "CA" | "CH" | "CI" | "CL" | "CM" | "CN" | "CO" | "CR" | "CY" | "CZ" | "DE" | "DK" | "DO" | "DZ" | "EC" | "EE" | "EG" | "ES" | "ET" | "FI" | "FR" | "GB" | "GE" | "GH" | "GR" | "GT" | "HK" | "HN" | "HR" | "HU" | "ID" | "IE" | "IL" | "IN" | "IQ" | "IR" | "IS" | "IT" | "JO" | "JP" | "KE" | "KG" | "KH" | "KR" | "KW" | "KZ" | "LA" | "LB" | "LK" | "LT" | "LU" | "LV" | "LY" | "MA" | "MD" | "ME" | "MK" | "MM" | "MN" | "MT" | "MX" | "MY" | "NG" | "NI" | "NL" | "NO" | "NP" | "NZ" | "PA" | "PE" | "PH" | "PK" | "PL" | "PT" | "PY" | "QA" | "RO" | "RS" | "RU" | "SA" | "SD" | "SE" | "SG" | "SI" | "SK" | "SN" | "SV" | "TH" | "TN" | "TR" | "TW" | "TZ" | "UA" | "UG" | "US" | "UY" | "UZ" | "VE" | "VN" | "XK" | "ZA" | "ZM" | "ZW";
  "subdivision"?: "AB" | "AK" | "AL" | "AR" | "AZ" | "BC" | "CA" | "CO" | "CT" | "DC" | "DE" | "FL" | "GA" | "HI" | "IA" | "ID" | "IL" | "IN" | "KS" | "KY" | "LA" | "MA" | "MB" | "MD" | "ME" | "MI" | "MN" | "MO" | "MS" | "MT" | "NB" | "NC" | "ND" | "NE" | "NH" | "NJ" | "NL" | "NM" | "NS" | "NT" | "NU" | "NV" | "NY" | "OH" | "OK" | "ON" | "OR" | "PA" | "PE" | "QC" | "RI" | "SC" | "SD" | "SK" | "TN" | "TX" | "UT" | "VA" | "VT" | "WA" | "WI" | "WV" | "WY" | "YT";
}

export type FlashscoreTournamentSeasonsResponse = CrawloraResponse<ModelFlashscoreTournamentSeasonsResponseDoc>;
export interface FlashscoreTournamentSeasonsParams {
  "path": string;
}

export type FlashscoreTournamentStandingsResponse = CrawloraResponse<ModelFlashscoreTournamentStandingsResponseDoc>;
export interface FlashscoreTournamentStandingsParams {
  "path": string;
  "view"?: "overall" | "home" | "away" | "form_overall" | "form_home" | "form_away" | "overunder_overall" | "overunder_home" | "overunder_away" | "htft_overall" | "htft_home" | "htft_away" | "top_scorers";
}

export type FlashscoreTournamentStandingsViewsResponse = CrawloraResponse<ModelFlashscoreTournamentStandingsViewsResponseDoc>;
export interface FlashscoreTournamentStandingsViewsParams {
  "path": string;
}

export interface FlashscoreService {
  calendar<T = FlashscoreCalendarResponse>(params: FlashscoreCalendarParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  calendarCategories<T = FlashscoreCalendarCategoriesResponse>(params?: FlashscoreCalendarCategoriesParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  competitions<T = FlashscoreCompetitionsResponse>(params: FlashscoreCompetitionsParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  entityNews<T = FlashscoreEntityNewsResponse>(params: FlashscoreEntityNewsParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  matchBoxScore<T = FlashscoreMatchBoxScoreResponse>(params: FlashscoreMatchBoxScoreParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  matchDarts<T = FlashscoreMatchDartsResponse>(params: FlashscoreMatchDartsParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  matchH2h<T = FlashscoreMatchH2hResponse>(params: FlashscoreMatchH2hParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  matchHighlights<T = FlashscoreMatchHighlightsResponse>(params: FlashscoreMatchHighlightsParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  matchInfo<T = FlashscoreMatchInfoResponse>(params: FlashscoreMatchInfoParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  matchLineups<T = FlashscoreMatchLineupsResponse>(params: FlashscoreMatchLineupsParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  matchMissingPlayers<T = FlashscoreMatchMissingPlayersResponse>(params: FlashscoreMatchMissingPlayersParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  matchMomentum<T = FlashscoreMatchMomentumResponse>(params: FlashscoreMatchMomentumParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  matchNews<T = FlashscoreMatchNewsResponse>(params: FlashscoreMatchNewsParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  matchOdds<T = FlashscoreMatchOddsResponse>(params: FlashscoreMatchOddsParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  matchPlayerStats<T = FlashscoreMatchPlayerStatsResponse>(params: FlashscoreMatchPlayerStatsParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  matchPointByPoint<T = FlashscoreMatchPointByPointResponse>(params: FlashscoreMatchPointByPointParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  matchPredictedLineups<T = FlashscoreMatchPredictedLineupsResponse>(params: FlashscoreMatchPredictedLineupsParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  matchReport<T = FlashscoreMatchReportResponse>(params: FlashscoreMatchReportParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  matchStandings<T = FlashscoreMatchStandingsResponse>(params: FlashscoreMatchStandingsParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  matchStats<T = FlashscoreMatchStatsResponse>(params: FlashscoreMatchStatsParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  matchTv<T = FlashscoreMatchTvResponse>(params: FlashscoreMatchTvParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  navigation<T = FlashscoreNavigationResponse>(params?: FlashscoreNavigationParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  news<T = FlashscoreNewsResponse>(params?: FlashscoreNewsParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  newsArticle<T = FlashscoreNewsArticleResponse>(params: FlashscoreNewsArticleParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  newsArticleBody<T = FlashscoreNewsArticleBodyResponse>(params: FlashscoreNewsArticleBodyParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  newsCategories<T = FlashscoreNewsCategoriesResponse>(params?: FlashscoreNewsCategoriesParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  newsMostRead<T = FlashscoreNewsMostReadResponse>(params?: FlashscoreNewsMostReadParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  oddsGeos<T = FlashscoreOddsGeosResponse>(params?: FlashscoreOddsGeosParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  player<T = FlashscorePlayerResponse>(params: FlashscorePlayerParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  playerFixtures<T = FlashscorePlayerFixturesResponse>(params: FlashscorePlayerFixturesParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  playerInjuries<T = FlashscorePlayerInjuriesResponse>(params: FlashscorePlayerInjuriesParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  playerMatchLog<T = FlashscorePlayerMatchLogResponse>(params: FlashscorePlayerMatchLogParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  playerNews<T = FlashscorePlayerNewsResponse>(params: FlashscorePlayerNewsParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  playerResults<T = FlashscorePlayerResultsResponse>(params: FlashscorePlayerResultsParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  playerTransfers<T = FlashscorePlayerTransfersResponse>(params: FlashscorePlayerTransfersParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  rankingCategories<T = FlashscoreRankingCategoriesResponse>(params?: FlashscoreRankingCategoriesParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  rankings<T = FlashscoreRankingsResponse>(params: FlashscoreRankingsParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  scores<T = FlashscoreScoresResponse>(params: FlashscoreScoresParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  search<T = FlashscoreSearchResponse>(params: FlashscoreSearchParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  sports<T = FlashscoreSportsResponse>(params?: FlashscoreSportsParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  team<T = FlashscoreTeamResponse>(params: FlashscoreTeamParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  teamFixtures<T = FlashscoreTeamFixturesResponse>(params: FlashscoreTeamFixturesParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  teamNews<T = FlashscoreTeamNewsResponse>(params: FlashscoreTeamNewsParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  teamOutrightOdds<T = FlashscoreTeamOutrightOddsResponse>(params: FlashscoreTeamOutrightOddsParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  teamResults<T = FlashscoreTeamResultsResponse>(params: FlashscoreTeamResultsParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  teamSquad<T = FlashscoreTeamSquadResponse>(params: FlashscoreTeamSquadParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  teamTransfers<T = FlashscoreTeamTransfersResponse>(params: FlashscoreTeamTransfersParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  topSearch<T = FlashscoreTopSearchResponse>(params?: FlashscoreTopSearchParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  tournamentArchiveSeasons<T = FlashscoreTournamentArchiveSeasonsResponse>(params: FlashscoreTournamentArchiveSeasonsParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  tournamentEvents<T = FlashscoreTournamentEventsResponse>(params: FlashscoreTournamentEventsParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  tournamentOutrightOdds<T = FlashscoreTournamentOutrightOddsResponse>(params: FlashscoreTournamentOutrightOddsParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  tournamentSeasons<T = FlashscoreTournamentSeasonsResponse>(params: FlashscoreTournamentSeasonsParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  tournamentStandings<T = FlashscoreTournamentStandingsResponse>(params: FlashscoreTournamentStandingsParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  tournamentStandingsViews<T = FlashscoreTournamentStandingsViewsResponse>(params: FlashscoreTournamentStandingsViewsParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
}

export interface CrawloraGeneratedGroups {
  flashscore: FlashscoreService;
}

export interface OperationParamsMap {
  "flashscore-calendar": FlashscoreCalendarParams;
  "flashscore-calendar-categories": FlashscoreCalendarCategoriesParams;
  "flashscore-competitions": FlashscoreCompetitionsParams;
  "flashscore-entity-news": FlashscoreEntityNewsParams;
  "flashscore-match-box-score": FlashscoreMatchBoxScoreParams;
  "flashscore-match-darts": FlashscoreMatchDartsParams;
  "flashscore-match-h2h": FlashscoreMatchH2hParams;
  "flashscore-match-highlights": FlashscoreMatchHighlightsParams;
  "flashscore-match-info": FlashscoreMatchInfoParams;
  "flashscore-match-lineups": FlashscoreMatchLineupsParams;
  "flashscore-match-missing-players": FlashscoreMatchMissingPlayersParams;
  "flashscore-match-momentum": FlashscoreMatchMomentumParams;
  "flashscore-match-news": FlashscoreMatchNewsParams;
  "flashscore-match-odds": FlashscoreMatchOddsParams;
  "flashscore-match-player-stats": FlashscoreMatchPlayerStatsParams;
  "flashscore-match-point-by-point": FlashscoreMatchPointByPointParams;
  "flashscore-match-predicted-lineups": FlashscoreMatchPredictedLineupsParams;
  "flashscore-match-report": FlashscoreMatchReportParams;
  "flashscore-match-standings": FlashscoreMatchStandingsParams;
  "flashscore-match-stats": FlashscoreMatchStatsParams;
  "flashscore-match-tv": FlashscoreMatchTvParams;
  "flashscore-navigation": FlashscoreNavigationParams;
  "flashscore-news": FlashscoreNewsParams;
  "flashscore-news-article": FlashscoreNewsArticleParams;
  "flashscore-news-article-body": FlashscoreNewsArticleBodyParams;
  "flashscore-news-categories": FlashscoreNewsCategoriesParams;
  "flashscore-news-most-read": FlashscoreNewsMostReadParams;
  "flashscore-odds-geos": FlashscoreOddsGeosParams;
  "flashscore-player": FlashscorePlayerParams;
  "flashscore-player-fixtures": FlashscorePlayerFixturesParams;
  "flashscore-player-injuries": FlashscorePlayerInjuriesParams;
  "flashscore-player-match-log": FlashscorePlayerMatchLogParams;
  "flashscore-player-news": FlashscorePlayerNewsParams;
  "flashscore-player-results": FlashscorePlayerResultsParams;
  "flashscore-player-transfers": FlashscorePlayerTransfersParams;
  "flashscore-ranking-categories": FlashscoreRankingCategoriesParams;
  "flashscore-rankings": FlashscoreRankingsParams;
  "flashscore-scores": FlashscoreScoresParams;
  "flashscore-search": FlashscoreSearchParams;
  "flashscore-sports": FlashscoreSportsParams;
  "flashscore-team": FlashscoreTeamParams;
  "flashscore-team-fixtures": FlashscoreTeamFixturesParams;
  "flashscore-team-news": FlashscoreTeamNewsParams;
  "flashscore-team-outright-odds": FlashscoreTeamOutrightOddsParams;
  "flashscore-team-results": FlashscoreTeamResultsParams;
  "flashscore-team-squad": FlashscoreTeamSquadParams;
  "flashscore-team-transfers": FlashscoreTeamTransfersParams;
  "flashscore-top-search": FlashscoreTopSearchParams;
  "flashscore-tournament-archive-seasons": FlashscoreTournamentArchiveSeasonsParams;
  "flashscore-tournament-events": FlashscoreTournamentEventsParams;
  "flashscore-tournament-outright-odds": FlashscoreTournamentOutrightOddsParams;
  "flashscore-tournament-seasons": FlashscoreTournamentSeasonsParams;
  "flashscore-tournament-standings": FlashscoreTournamentStandingsParams;
  "flashscore-tournament-standings-views": FlashscoreTournamentStandingsViewsParams;
}

export interface OperationResponseMap {
  "flashscore-calendar": FlashscoreCalendarResponse;
  "flashscore-calendar-categories": FlashscoreCalendarCategoriesResponse;
  "flashscore-competitions": FlashscoreCompetitionsResponse;
  "flashscore-entity-news": FlashscoreEntityNewsResponse;
  "flashscore-match-box-score": FlashscoreMatchBoxScoreResponse;
  "flashscore-match-darts": FlashscoreMatchDartsResponse;
  "flashscore-match-h2h": FlashscoreMatchH2hResponse;
  "flashscore-match-highlights": FlashscoreMatchHighlightsResponse;
  "flashscore-match-info": FlashscoreMatchInfoResponse;
  "flashscore-match-lineups": FlashscoreMatchLineupsResponse;
  "flashscore-match-missing-players": FlashscoreMatchMissingPlayersResponse;
  "flashscore-match-momentum": FlashscoreMatchMomentumResponse;
  "flashscore-match-news": FlashscoreMatchNewsResponse;
  "flashscore-match-odds": FlashscoreMatchOddsResponse;
  "flashscore-match-player-stats": FlashscoreMatchPlayerStatsResponse;
  "flashscore-match-point-by-point": FlashscoreMatchPointByPointResponse;
  "flashscore-match-predicted-lineups": FlashscoreMatchPredictedLineupsResponse;
  "flashscore-match-report": FlashscoreMatchReportResponse;
  "flashscore-match-standings": FlashscoreMatchStandingsResponse;
  "flashscore-match-stats": FlashscoreMatchStatsResponse;
  "flashscore-match-tv": FlashscoreMatchTvResponse;
  "flashscore-navigation": FlashscoreNavigationResponse;
  "flashscore-news": FlashscoreNewsResponse;
  "flashscore-news-article": FlashscoreNewsArticleResponse;
  "flashscore-news-article-body": FlashscoreNewsArticleBodyResponse;
  "flashscore-news-categories": FlashscoreNewsCategoriesResponse;
  "flashscore-news-most-read": FlashscoreNewsMostReadResponse;
  "flashscore-odds-geos": FlashscoreOddsGeosResponse;
  "flashscore-player": FlashscorePlayerResponse;
  "flashscore-player-fixtures": FlashscorePlayerFixturesResponse;
  "flashscore-player-injuries": FlashscorePlayerInjuriesResponse;
  "flashscore-player-match-log": FlashscorePlayerMatchLogResponse;
  "flashscore-player-news": FlashscorePlayerNewsResponse;
  "flashscore-player-results": FlashscorePlayerResultsResponse;
  "flashscore-player-transfers": FlashscorePlayerTransfersResponse;
  "flashscore-ranking-categories": FlashscoreRankingCategoriesResponse;
  "flashscore-rankings": FlashscoreRankingsResponse;
  "flashscore-scores": FlashscoreScoresResponse;
  "flashscore-search": FlashscoreSearchResponse;
  "flashscore-sports": FlashscoreSportsResponse;
  "flashscore-team": FlashscoreTeamResponse;
  "flashscore-team-fixtures": FlashscoreTeamFixturesResponse;
  "flashscore-team-news": FlashscoreTeamNewsResponse;
  "flashscore-team-outright-odds": FlashscoreTeamOutrightOddsResponse;
  "flashscore-team-results": FlashscoreTeamResultsResponse;
  "flashscore-team-squad": FlashscoreTeamSquadResponse;
  "flashscore-team-transfers": FlashscoreTeamTransfersResponse;
  "flashscore-top-search": FlashscoreTopSearchResponse;
  "flashscore-tournament-archive-seasons": FlashscoreTournamentArchiveSeasonsResponse;
  "flashscore-tournament-events": FlashscoreTournamentEventsResponse;
  "flashscore-tournament-outright-odds": FlashscoreTournamentOutrightOddsResponse;
  "flashscore-tournament-seasons": FlashscoreTournamentSeasonsResponse;
  "flashscore-tournament-standings": FlashscoreTournamentStandingsResponse;
  "flashscore-tournament-standings-views": FlashscoreTournamentStandingsViewsResponse;
}

export interface OperationRequiredParamsMap {
  "flashscore-calendar": true;
  "flashscore-calendar-categories": false;
  "flashscore-competitions": true;
  "flashscore-entity-news": true;
  "flashscore-match-box-score": true;
  "flashscore-match-darts": true;
  "flashscore-match-h2h": true;
  "flashscore-match-highlights": true;
  "flashscore-match-info": true;
  "flashscore-match-lineups": true;
  "flashscore-match-missing-players": true;
  "flashscore-match-momentum": true;
  "flashscore-match-news": true;
  "flashscore-match-odds": true;
  "flashscore-match-player-stats": true;
  "flashscore-match-point-by-point": true;
  "flashscore-match-predicted-lineups": true;
  "flashscore-match-report": true;
  "flashscore-match-standings": true;
  "flashscore-match-stats": true;
  "flashscore-match-tv": true;
  "flashscore-navigation": false;
  "flashscore-news": false;
  "flashscore-news-article": true;
  "flashscore-news-article-body": true;
  "flashscore-news-categories": false;
  "flashscore-news-most-read": false;
  "flashscore-odds-geos": false;
  "flashscore-player": true;
  "flashscore-player-fixtures": true;
  "flashscore-player-injuries": true;
  "flashscore-player-match-log": true;
  "flashscore-player-news": true;
  "flashscore-player-results": true;
  "flashscore-player-transfers": true;
  "flashscore-ranking-categories": false;
  "flashscore-rankings": true;
  "flashscore-scores": true;
  "flashscore-search": true;
  "flashscore-sports": false;
  "flashscore-team": true;
  "flashscore-team-fixtures": true;
  "flashscore-team-news": true;
  "flashscore-team-outright-odds": true;
  "flashscore-team-results": true;
  "flashscore-team-squad": true;
  "flashscore-team-transfers": true;
  "flashscore-top-search": false;
  "flashscore-tournament-archive-seasons": true;
  "flashscore-tournament-events": true;
  "flashscore-tournament-outright-odds": true;
  "flashscore-tournament-seasons": true;
  "flashscore-tournament-standings": true;
  "flashscore-tournament-standings-views": true;
}

export type OperationId = keyof OperationParamsMap;

export type OperationRequestArgs<I extends OperationId> =
  OperationRequiredParamsMap[I] extends true
    ? [params: OperationParamsMap[I], options?: import('./index.js').CrawloraRequestOptions]
    : [params?: OperationParamsMap[I], options?: import('./index.js').CrawloraRequestOptions];

export type OperationIdLiteral =
  | "flashscore-calendar"
  | "flashscore-calendar-categories"
  | "flashscore-competitions"
  | "flashscore-entity-news"
  | "flashscore-match-box-score"
  | "flashscore-match-darts"
  | "flashscore-match-h2h"
  | "flashscore-match-highlights"
  | "flashscore-match-info"
  | "flashscore-match-lineups"
  | "flashscore-match-missing-players"
  | "flashscore-match-momentum"
  | "flashscore-match-news"
  | "flashscore-match-odds"
  | "flashscore-match-player-stats"
  | "flashscore-match-point-by-point"
  | "flashscore-match-predicted-lineups"
  | "flashscore-match-report"
  | "flashscore-match-standings"
  | "flashscore-match-stats"
  | "flashscore-match-tv"
  | "flashscore-navigation"
  | "flashscore-news"
  | "flashscore-news-article"
  | "flashscore-news-article-body"
  | "flashscore-news-categories"
  | "flashscore-news-most-read"
  | "flashscore-odds-geos"
  | "flashscore-player"
  | "flashscore-player-fixtures"
  | "flashscore-player-injuries"
  | "flashscore-player-match-log"
  | "flashscore-player-news"
  | "flashscore-player-results"
  | "flashscore-player-transfers"
  | "flashscore-ranking-categories"
  | "flashscore-rankings"
  | "flashscore-scores"
  | "flashscore-search"
  | "flashscore-sports"
  | "flashscore-team"
  | "flashscore-team-fixtures"
  | "flashscore-team-news"
  | "flashscore-team-outright-odds"
  | "flashscore-team-results"
  | "flashscore-team-squad"
  | "flashscore-team-transfers"
  | "flashscore-top-search"
  | "flashscore-tournament-archive-seasons"
  | "flashscore-tournament-events"
  | "flashscore-tournament-outright-odds"
  | "flashscore-tournament-seasons"
  | "flashscore-tournament-standings"
  | "flashscore-tournament-standings-views";

export declare const OperationIds: Readonly<{
  FlashscoreCalendar: "flashscore-calendar";
  FlashscoreCalendarCategories: "flashscore-calendar-categories";
  FlashscoreCompetitions: "flashscore-competitions";
  FlashscoreEntityNews: "flashscore-entity-news";
  FlashscoreMatchBoxScore: "flashscore-match-box-score";
  FlashscoreMatchDarts: "flashscore-match-darts";
  FlashscoreMatchH2h: "flashscore-match-h2h";
  FlashscoreMatchHighlights: "flashscore-match-highlights";
  FlashscoreMatchInfo: "flashscore-match-info";
  FlashscoreMatchLineups: "flashscore-match-lineups";
  FlashscoreMatchMissingPlayers: "flashscore-match-missing-players";
  FlashscoreMatchMomentum: "flashscore-match-momentum";
  FlashscoreMatchNews: "flashscore-match-news";
  FlashscoreMatchOdds: "flashscore-match-odds";
  FlashscoreMatchPlayerStats: "flashscore-match-player-stats";
  FlashscoreMatchPointByPoint: "flashscore-match-point-by-point";
  FlashscoreMatchPredictedLineups: "flashscore-match-predicted-lineups";
  FlashscoreMatchReport: "flashscore-match-report";
  FlashscoreMatchStandings: "flashscore-match-standings";
  FlashscoreMatchStats: "flashscore-match-stats";
  FlashscoreMatchTv: "flashscore-match-tv";
  FlashscoreNavigation: "flashscore-navigation";
  FlashscoreNews: "flashscore-news";
  FlashscoreNewsArticle: "flashscore-news-article";
  FlashscoreNewsArticleBody: "flashscore-news-article-body";
  FlashscoreNewsCategories: "flashscore-news-categories";
  FlashscoreNewsMostRead: "flashscore-news-most-read";
  FlashscoreOddsGeos: "flashscore-odds-geos";
  FlashscorePlayer: "flashscore-player";
  FlashscorePlayerFixtures: "flashscore-player-fixtures";
  FlashscorePlayerInjuries: "flashscore-player-injuries";
  FlashscorePlayerMatchLog: "flashscore-player-match-log";
  FlashscorePlayerNews: "flashscore-player-news";
  FlashscorePlayerResults: "flashscore-player-results";
  FlashscorePlayerTransfers: "flashscore-player-transfers";
  FlashscoreRankingCategories: "flashscore-ranking-categories";
  FlashscoreRankings: "flashscore-rankings";
  FlashscoreScores: "flashscore-scores";
  FlashscoreSearch: "flashscore-search";
  FlashscoreSports: "flashscore-sports";
  FlashscoreTeam: "flashscore-team";
  FlashscoreTeamFixtures: "flashscore-team-fixtures";
  FlashscoreTeamNews: "flashscore-team-news";
  FlashscoreTeamOutrightOdds: "flashscore-team-outright-odds";
  FlashscoreTeamResults: "flashscore-team-results";
  FlashscoreTeamSquad: "flashscore-team-squad";
  FlashscoreTeamTransfers: "flashscore-team-transfers";
  FlashscoreTopSearch: "flashscore-top-search";
  FlashscoreTournamentArchiveSeasons: "flashscore-tournament-archive-seasons";
  FlashscoreTournamentEvents: "flashscore-tournament-events";
  FlashscoreTournamentOutrightOdds: "flashscore-tournament-outright-odds";
  FlashscoreTournamentSeasons: "flashscore-tournament-seasons";
  FlashscoreTournamentStandings: "flashscore-tournament-standings";
  FlashscoreTournamentStandingsViews: "flashscore-tournament-standings-views";
}>;
