// Code generated by the Crawlora platform SDK generator. DO NOT EDIT.

package flashscore

import (
	"context"
	"sort"

	crawlora "github.com/Crawlora-org/crawlora-go-sdk"
)

type parameterDefinition struct {
	Name             string
	In               string
	Type             string
	CollectionFormat string
	Required         bool
	Enum             []string
}

type operationDefinition struct {
	Method      string
	Path        string
	PathParams  []string
	QueryParams []parameterDefinition
	Produces    []string
	Security    []string
}

var operations = map[string]operationDefinition{
	"flashscore-calendar":                   operationDefinition{Method: "GET", Path: "/flashscore/calendar", PathParams: nil, QueryParams: []parameterDefinition{parameterDefinition{Name: "category", In: "query", Type: "string", Required: true, Enum: []string{"tennis-atp", "tennis-wta", "golf-pga", "golf-dp-world", "badminton-bwf", "motorsport-f1"}}}, Produces: []string{"application/json"}, Security: []string{"ApiKeyAuth"}},
	"flashscore-calendar-categories":        operationDefinition{Method: "GET", Path: "/flashscore/calendar-categories", PathParams: nil, QueryParams: nil, Produces: []string{"application/json"}, Security: []string{"ApiKeyAuth"}},
	"flashscore-competitions":               operationDefinition{Method: "GET", Path: "/flashscore/competitions", PathParams: nil, QueryParams: []parameterDefinition{parameterDefinition{Name: "sport", In: "query", Type: "string", Required: true, Enum: []string{"football", "tennis", "basketball", "hockey", "golf", "formula-1", "baseball", "snooker", "american-football", "aussie-rules", "badminton", "bandy", "beach-soccer", "beach-volleyball", "boxing", "cricket", "cycling", "darts", "esports", "field-hockey", "floorball", "futsal", "handball", "horse-racing", "kabaddi", "mma", "motorsport", "netball", "pesapallo", "rugby-league", "rugby-union", "table-tennis", "volleyball", "water-polo", "winter-sports"}}, parameterDefinition{Name: "day_offset", In: "query", Type: "integer"}}, Produces: []string{"application/json"}, Security: []string{"ApiKeyAuth"}},
	"flashscore-match-h2h":                  operationDefinition{Method: "GET", Path: "/flashscore/match-h2h", PathParams: nil, QueryParams: []parameterDefinition{parameterDefinition{Name: "id", In: "query", Type: "string", Required: true}}, Produces: []string{"application/json"}, Security: []string{"ApiKeyAuth"}},
	"flashscore-match-highlights":           operationDefinition{Method: "GET", Path: "/flashscore/match-highlights", PathParams: nil, QueryParams: []parameterDefinition{parameterDefinition{Name: "id", In: "query", Type: "string", Required: true}}, Produces: []string{"application/json"}, Security: []string{"ApiKeyAuth"}},
	"flashscore-match-info":                 operationDefinition{Method: "GET", Path: "/flashscore/match-info", PathParams: nil, QueryParams: []parameterDefinition{parameterDefinition{Name: "id", In: "query", Type: "string", Required: true}}, Produces: []string{"application/json"}, Security: []string{"ApiKeyAuth"}},
	"flashscore-match-lineups":              operationDefinition{Method: "GET", Path: "/flashscore/match-lineups", PathParams: nil, QueryParams: []parameterDefinition{parameterDefinition{Name: "id", In: "query", Type: "string", Required: true}}, Produces: []string{"application/json"}, Security: []string{"ApiKeyAuth"}},
	"flashscore-match-news":                 operationDefinition{Method: "GET", Path: "/flashscore/match-news", PathParams: nil, QueryParams: []parameterDefinition{parameterDefinition{Name: "id", In: "query", Type: "string", Required: true}}, Produces: []string{"application/json"}, Security: []string{"ApiKeyAuth"}},
	"flashscore-match-standings":            operationDefinition{Method: "GET", Path: "/flashscore/match-standings", PathParams: nil, QueryParams: []parameterDefinition{parameterDefinition{Name: "id", In: "query", Type: "string", Required: true}, parameterDefinition{Name: "view", In: "query", Type: "string", Enum: []string{"overall", "home", "away", "form_overall", "overunder_overall", "form_home", "form_away", "top_scorers", "htft_overall", "htft_home", "htft_away", "live_overall", "overunder_home", "overunder_away"}}}, Produces: []string{"application/json"}, Security: []string{"ApiKeyAuth"}},
	"flashscore-match-stats":                operationDefinition{Method: "GET", Path: "/flashscore/match-stats", PathParams: nil, QueryParams: []parameterDefinition{parameterDefinition{Name: "id", In: "query", Type: "string", Required: true}}, Produces: []string{"application/json"}, Security: []string{"ApiKeyAuth"}},
	"flashscore-navigation":                 operationDefinition{Method: "GET", Path: "/flashscore/navigation", PathParams: nil, QueryParams: []parameterDefinition{parameterDefinition{Name: "path", In: "query", Type: "string"}}, Produces: []string{"application/json"}, Security: []string{"ApiKeyAuth"}},
	"flashscore-news":                       operationDefinition{Method: "GET", Path: "/flashscore/news", PathParams: nil, QueryParams: []parameterDefinition{parameterDefinition{Name: "category", In: "query", Type: "string", Enum: []string{"all", "football", "uefa-nations-league", "tennis", "features", "premier-league", "nfl", "mlb", "nba", "nhl", "formula-1", "champions-league", "europa-league", "conference-league", "darts", "snooker", "golf", "road-cycling", "laliga", "bundesliga", "serie-a", "ligue-1", "badminton", "handball", "hockey", "basketball", "cricket", "rugby-union", "athletics", "baseball", "fifa", "rugby-league", "motorsport", "aussie-rules", "flashscore-ratings", "american-sports", "african-football", "combat-sports", "winter-sports", "transfer-news"}}, parameterDefinition{Name: "page", In: "query", Type: "integer"}}, Produces: []string{"application/json"}, Security: []string{"ApiKeyAuth"}},
	"flashscore-news-article":               operationDefinition{Method: "GET", Path: "/flashscore/news-article", PathParams: nil, QueryParams: []parameterDefinition{parameterDefinition{Name: "id", In: "query", Type: "string", Required: true}}, Produces: []string{"application/json"}, Security: []string{"ApiKeyAuth"}},
	"flashscore-news-categories":            operationDefinition{Method: "GET", Path: "/flashscore/news-categories", PathParams: nil, QueryParams: nil, Produces: []string{"application/json"}, Security: []string{"ApiKeyAuth"}},
	"flashscore-ranking-categories":         operationDefinition{Method: "GET", Path: "/flashscore/ranking-categories", PathParams: nil, QueryParams: nil, Produces: []string{"application/json"}, Security: []string{"ApiKeyAuth"}},
	"flashscore-rankings":                   operationDefinition{Method: "GET", Path: "/flashscore/rankings", PathParams: nil, QueryParams: []parameterDefinition{parameterDefinition{Name: "category", In: "query", Type: "string", Required: true, Enum: []string{"fifa", "tennis-atp", "tennis-wta", "tennis-atp-race", "tennis-wta-race", "tennis-atp-doubles", "tennis-wta-doubles", "tennis-atp-doubles-race", "tennis-wta-doubles-race", "badminton-bwf-singles-men", "badminton-bwf-singles-women", "badminton-bwf-doubles-men", "badminton-bwf-doubles-women", "badminton-bwf-mixed-doubles", "golf-owgr", "golf-wwgr", "golf-pga-fedexcup", "golf-pga-money", "golf-dp-world-tour", "golf-lpga", "golf-asian-tour", "golf-japan-tour", "golf-sunshine-tour", "golf-korn-ferry", "golf-champions-tour", "darts-world-ranking", "snooker-world-ranking", "tennis-atp-live", "tennis-wta-live", "tennis-atp-race-live", "tennis-wta-race-live", "tennis-atp-doubles-live", "tennis-wta-doubles-live", "tennis-atp-doubles-race-live", "tennis-wta-doubles-race-live"}}}, Produces: []string{"application/json"}, Security: []string{"ApiKeyAuth"}},
	"flashscore-scores":                     operationDefinition{Method: "GET", Path: "/flashscore/scores", PathParams: nil, QueryParams: []parameterDefinition{parameterDefinition{Name: "sport", In: "query", Type: "string", Required: true, Enum: []string{"football", "tennis", "basketball", "hockey", "golf", "formula-1", "baseball", "snooker", "american-football", "aussie-rules", "badminton", "bandy", "beach-soccer", "beach-volleyball", "boxing", "cricket", "cycling", "darts", "esports", "field-hockey", "floorball", "futsal", "handball", "horse-racing", "kabaddi", "mma", "motorsport", "netball", "pesapallo", "rugby-league", "rugby-union", "table-tennis", "volleyball", "water-polo", "winter-sports"}}, parameterDefinition{Name: "day_offset", In: "query", Type: "integer"}}, Produces: []string{"application/json"}, Security: []string{"ApiKeyAuth"}},
	"flashscore-search":                     operationDefinition{Method: "GET", Path: "/flashscore/search", PathParams: nil, QueryParams: []parameterDefinition{parameterDefinition{Name: "q", In: "query", Type: "string", Required: true}}, Produces: []string{"application/json"}, Security: []string{"ApiKeyAuth"}},
	"flashscore-sports":                     operationDefinition{Method: "GET", Path: "/flashscore/sports", PathParams: nil, QueryParams: nil, Produces: []string{"application/json"}, Security: []string{"ApiKeyAuth"}},
	"flashscore-top-search":                 operationDefinition{Method: "GET", Path: "/flashscore/top-search", PathParams: nil, QueryParams: nil, Produces: []string{"application/json"}, Security: []string{"ApiKeyAuth"}},
	"flashscore-tournament-events":          operationDefinition{Method: "GET", Path: "/flashscore/tournament-events", PathParams: nil, QueryParams: []parameterDefinition{parameterDefinition{Name: "path", In: "query", Type: "string", Required: true}, parameterDefinition{Name: "page", In: "query", Type: "integer"}}, Produces: []string{"application/json"}, Security: []string{"ApiKeyAuth"}},
	"flashscore-tournament-seasons":         operationDefinition{Method: "GET", Path: "/flashscore/tournament-seasons", PathParams: nil, QueryParams: []parameterDefinition{parameterDefinition{Name: "path", In: "query", Type: "string", Required: true}}, Produces: []string{"application/json"}, Security: []string{"ApiKeyAuth"}},
	"flashscore-tournament-standings":       operationDefinition{Method: "GET", Path: "/flashscore/tournament-standings", PathParams: nil, QueryParams: []parameterDefinition{parameterDefinition{Name: "path", In: "query", Type: "string", Required: true}, parameterDefinition{Name: "view", In: "query", Type: "string", Enum: []string{"overall", "home", "away", "form_overall", "form_home", "form_away", "overunder_overall", "overunder_home", "overunder_away", "htft_overall", "htft_home", "htft_away", "top_scorers"}}}, Produces: []string{"application/json"}, Security: []string{"ApiKeyAuth"}},
	"flashscore-tournament-standings-views": operationDefinition{Method: "GET", Path: "/flashscore/tournament-standings-views", PathParams: nil, QueryParams: []parameterDefinition{parameterDefinition{Name: "path", In: "query", Type: "string", Required: true}}, Produces: []string{"application/json"}, Security: []string{"ApiKeyAuth"}},
}

// OperationCount reports how many selected-platform operations this module exposes.
const OperationCount = 24

// OperationIDs returns the selected operation IDs in stable sorted order.
func OperationIDs() []string {
	ids := make([]string, 0, len(operations))
	for id := range operations {
		ids = append(ids, id)
	}
	sort.Strings(ids)
	return ids
}

// Calendar calls the flashscore-calendar operation.
func (c *Client) Calendar(ctx context.Context, params crawlora.Params) (any, error) {
	return c.Call(ctx, "flashscore-calendar", params)
}

// CalendarCategories calls the flashscore-calendar-categories operation.
func (c *Client) CalendarCategories(ctx context.Context, params crawlora.Params) (any, error) {
	return c.Call(ctx, "flashscore-calendar-categories", params)
}

// Competitions calls the flashscore-competitions operation.
func (c *Client) Competitions(ctx context.Context, params crawlora.Params) (any, error) {
	return c.Call(ctx, "flashscore-competitions", params)
}

// MatchH2h calls the flashscore-match-h2h operation.
func (c *Client) MatchH2h(ctx context.Context, params crawlora.Params) (any, error) {
	return c.Call(ctx, "flashscore-match-h2h", params)
}

// MatchHighlights calls the flashscore-match-highlights operation.
func (c *Client) MatchHighlights(ctx context.Context, params crawlora.Params) (any, error) {
	return c.Call(ctx, "flashscore-match-highlights", params)
}

// MatchInfo calls the flashscore-match-info operation.
func (c *Client) MatchInfo(ctx context.Context, params crawlora.Params) (any, error) {
	return c.Call(ctx, "flashscore-match-info", params)
}

// MatchLineups calls the flashscore-match-lineups operation.
func (c *Client) MatchLineups(ctx context.Context, params crawlora.Params) (any, error) {
	return c.Call(ctx, "flashscore-match-lineups", params)
}

// MatchNews calls the flashscore-match-news operation.
func (c *Client) MatchNews(ctx context.Context, params crawlora.Params) (any, error) {
	return c.Call(ctx, "flashscore-match-news", params)
}

// MatchStandings calls the flashscore-match-standings operation.
func (c *Client) MatchStandings(ctx context.Context, params crawlora.Params) (any, error) {
	return c.Call(ctx, "flashscore-match-standings", params)
}

// MatchStats calls the flashscore-match-stats operation.
func (c *Client) MatchStats(ctx context.Context, params crawlora.Params) (any, error) {
	return c.Call(ctx, "flashscore-match-stats", params)
}

// Navigation calls the flashscore-navigation operation.
func (c *Client) Navigation(ctx context.Context, params crawlora.Params) (any, error) {
	return c.Call(ctx, "flashscore-navigation", params)
}

// News calls the flashscore-news operation.
func (c *Client) News(ctx context.Context, params crawlora.Params) (any, error) {
	return c.Call(ctx, "flashscore-news", params)
}

// NewsArticle calls the flashscore-news-article operation.
func (c *Client) NewsArticle(ctx context.Context, params crawlora.Params) (any, error) {
	return c.Call(ctx, "flashscore-news-article", params)
}

// NewsCategories calls the flashscore-news-categories operation.
func (c *Client) NewsCategories(ctx context.Context, params crawlora.Params) (any, error) {
	return c.Call(ctx, "flashscore-news-categories", params)
}

// RankingCategories calls the flashscore-ranking-categories operation.
func (c *Client) RankingCategories(ctx context.Context, params crawlora.Params) (any, error) {
	return c.Call(ctx, "flashscore-ranking-categories", params)
}

// Rankings calls the flashscore-rankings operation.
func (c *Client) Rankings(ctx context.Context, params crawlora.Params) (any, error) {
	return c.Call(ctx, "flashscore-rankings", params)
}

// Scores calls the flashscore-scores operation.
func (c *Client) Scores(ctx context.Context, params crawlora.Params) (any, error) {
	return c.Call(ctx, "flashscore-scores", params)
}

// Search calls the flashscore-search operation.
func (c *Client) Search(ctx context.Context, params crawlora.Params) (any, error) {
	return c.Call(ctx, "flashscore-search", params)
}

// Sports calls the flashscore-sports operation.
func (c *Client) Sports(ctx context.Context, params crawlora.Params) (any, error) {
	return c.Call(ctx, "flashscore-sports", params)
}

// TopSearch calls the flashscore-top-search operation.
func (c *Client) TopSearch(ctx context.Context, params crawlora.Params) (any, error) {
	return c.Call(ctx, "flashscore-top-search", params)
}

// TournamentEvents calls the flashscore-tournament-events operation.
func (c *Client) TournamentEvents(ctx context.Context, params crawlora.Params) (any, error) {
	return c.Call(ctx, "flashscore-tournament-events", params)
}

// TournamentSeasons calls the flashscore-tournament-seasons operation.
func (c *Client) TournamentSeasons(ctx context.Context, params crawlora.Params) (any, error) {
	return c.Call(ctx, "flashscore-tournament-seasons", params)
}

// TournamentStandings calls the flashscore-tournament-standings operation.
func (c *Client) TournamentStandings(ctx context.Context, params crawlora.Params) (any, error) {
	return c.Call(ctx, "flashscore-tournament-standings", params)
}

// TournamentStandingsViews calls the flashscore-tournament-standings-views operation.
func (c *Client) TournamentStandingsViews(ctx context.Context, params crawlora.Params) (any, error) {
	return c.Call(ctx, "flashscore-tournament-standings-views", params)
}
